### ISSUE TITLE
現存するロボットの状態を確認する

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/orne_or#1]

**Comment by Keita1Mori** [comment]
# 9/21
- 作業同伴者（林原、川鍋、三渕、西尾、馬場、森）
- 外装の取り外し

- 以下のドキュメントにまとめている
  - [サービスロボットパーツ確認](https://docs.google.com/document/d/1rdv991Sx0XImE8Ea1krGwOLIXFJztTYVnD_Idbi8EVA/edit#heading=h.m7zejiqxlyxf)
  - [ネジ調査](https://docs.google.com/document/d/1i-Win11bEPFp-3auYVUlOwqiNeFGU1ATYWkdk0yexmE/edit#heading=h.5ik1n7g3fhzc)

**Comment by MibuchiYuta** [comment]
作業が完了したのでcloseします
