### ISSUE TITLE
追加の部品確認

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_or#11]
アーム部分を作れるかの部品確認を再度行う．
![image](https://github.com/open-rdc/office_robot/assets/5755200/a5ceaead-fc7f-4bc5-9784-9d0a78d6739b)

**Comment by yasuohayashibara** [comment]
現在，見つかった部品を透明化して，不足する部品を目立たせるようにした．

![image](https://github.com/open-rdc/office_robot/assets/5755200/a95ae878-02b6-4ae0-b354-c8fd695ff8f2)

![image](https://github.com/open-rdc/office_robot/assets/5755200/3a734799-e4da-4fd8-af1a-c5470159d0fb)

**Comment by MibuchiYuta** [comment]
@KiyoshiroKawanabe @Keita1Mori その後の報告をお願いします。

**Comment by Keita1Mori** [comment]
上記以外に必要な追加部品はなかったので、issueをcloseします。
