### ISSUE TITLE
既存のロボットで自律移動をする

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/orne_or#14]
2024/2/8に千葉工業大学津田沼キャンパスで行われる**津田沼チャレンジ**への出走を目標に既存ロボットを屋外で自律移動をさせる。

**Comment by MibuchiYuta** [comment]
既存ロボットのうち、走行に必要な電子回路部分の固定が不安定のほか配線が一部されていないため #15 にて改良作業を行います。

**Comment by KiyoshiroKawanabe** [comment]
# 自律移動をさせる流れ
## dockerイメージのダウンロードとコンテナ作成

## コンテナ内での実行コマンド
有線のプロファイルを*hokuyo*にする
<img src='https://github.com/open-rdc/office_robot/assets/53420739/30f3d4d4-9122-45c8-8aa9-12b2e14bf3e8' width = 600>
- ypspurやモータ周りのノードを起動
`roslaunch orne_box_bringup office_robot.launch`
- ジョイスティックで動かす場合は以下を起動
`roslaunch icart_mini_driver teleop_joy.launch`
- LiDARで自分(ロボット)を認識させない
`roslaunch laser_filters box_filter_example.launch`
- waypointの起動
`roslaunch waypoint_server waypoint_server.launch`
- rvizの起動
`roslaunch orne_box_navigation_executor play_waypoints_nav_box.launch`
- 次のプランニングを開始する
`rosservice call /waypoint_manager/waypoint_server/switch_cancel`
緊急停止ボタンを解除すると動き出す。

**Comment by KiyoshiroKawanabe** [comment]
環境構築、使用したリポジトリなどをまとめる

**Comment by MibuchiYuta** [comment]
OfficeRobotを扱う研究グループとして共用PCを1台セットアップしました。 #17 に作業を記載しています。

**Comment by MibuchiYuta** [comment]
上記では open-rdc/orne_box をベースに作業していますが、以降では openrdc/office_robotをベースに開発する方針となりました。
#20 にてそのインストール方法と実行方法に関して作業しています。

**Comment by MibuchiYuta** [comment]
> 2024/2/8に千葉工業大学津田沼キャンパスで行われる**津田沼チャレンジ**への出走を目標に既存ロボットを屋外で自律移動をさせる。

ハードウェア故障により棄権したため、2024/3/23に開かれる津田沼チャレンジに目標を変更しています。

**Comment by KiyoshiroKawanabe** [comment]
現在のハードウェアで、津田沼キャンパスでの屋外自立走行ができることを確認しました。津田沼チャレンジは延期になりましたので、実績は何もないですが、当初の目標であった自立移動はできるようになったのでissueを閉じます。
@Keita1Mori 動画をこのissueに貼ってください。

**Comment by Keita1Mori** [comment]
# 自律移動した際の動画
[3/20の自律移動](https://drive.google.com/drive/folders/1--zUmkWtZwU7pKjSmca5Zk3pBEZhlJGu?usp=drive_link)
[3/21の自律移動](https://drive.google.com/drive/folders/1-1e4K2cC2hgwAO2oXnqAekmPNhPQX8sy?usp=drive_link)
