### ISSUE TITLE
屋外自立移動をさせるための既存ロボットの改良

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/orne_or#15]

**Comment by KiyoshiroKawanabe** [comment]
# LiDARの取り付け
写真のように3階にあったフレームを利用してLiDARを取り付けた。
<img src ="https://github.com/open-rdc/office_robot/assets/53420739/9eebea5f-be82-49d7-a413-93420d558e6e" width="400">
<img src ="https://github.com/open-rdc/office_robot/assets/53420739/b3a89e07-67b7-40ed-8796-1ad1ea80e73a" width="400">
# 回路基板保護部品の設計
回路基板を保護する部品を設計し3Dプリントで製作した。
モータドライバの下についている部品にはリレーをはめ込めるようにし、もともと空中に浮いていたリレーを固定させるようにした。
<img src ="https://github.com/open-rdc/office_robot/assets/53420739/387abc13-43a7-4b68-9b01-993d88f4a011" width="400">
<img src ="https://github.com/open-rdc/office_robot/assets/53420739/2875963f-ae0c-4d55-a9a6-f01b3ff4d3f9" width="400">
<img src ="https://github.com/open-rdc/office_robot/assets/53420739/96a16033-8112-40dd-849d-6bf6101a3d00" width="400">
二つの部品はどちらも基板の裏側と触れないよう、固定する四隅以外はざぐっている。
<img src ="https://github.com/open-rdc/office_robot/assets/53420739/ba9636d0-4ee0-453e-9165-cb447e7ae71b" width="400">

**Comment by MibuchiYuta** [comment]
# 回路ケースの取り付け
スイッチなどを除いた主要な電子回路をケース内に収納し、ケースを台車部分に固定した。
![IMG_1638](https://github.com/open-rdc/orne_or/assets/53966307/500d33f9-d125-46d3-8b13-579e74b875ba)
![IMG_1639](https://github.com/open-rdc/orne_or/assets/53966307/933c9eb9-9923-4eb1-b17e-e7dd2ad08b1f)

**Comment by MibuchiYuta** [comment]
必要な改良ができたためcloseします
