### ISSUE TITLE
レポジトリ名の決定

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_or#19]
ROSではレポジトリの名前がかぶると作業がしづらいので，固有の名前を割り当てることが好ましい．
あとで切り替えるのは大変なので，本日(2/2)決定したい．

**Comment by yasuohayashibara** [comment]
orne_or_xx

にする予定
屋外自律移動のメンバーの承認を得る必要あり

**Comment by MibuchiYuta** [comment]
主要のメンバーに承諾を得ました。

**Comment by MibuchiYuta** [comment]
決定したのでcloseします
