### ISSUE TITLE
部品、パーツの在庫

### ISSUE THREAD

**Issue by Keita1Mori** [open-rdc/orne_or#2]

**Comment by Keita1Mori** [comment]
# 9/22 段ボールに入っている、パーツ、ネジなどの在庫確認
## ネジ（アームに取り付けられているの含めない）
- M5×5 皿ネジ　１本
- M3×7.7 鍋ネジ　４本
- M3×5.5 鍋ネジ　１本
- M3×14.6 鍋ネジ　２本
- M3×5 六角ネジ　１本
- M3 六角ナット　３個
- M2.6×14.6 鍋ネジ　３本
- M2.6×29.5 鍋ネジ　１本
- M2.6×15.7 鍋ネジ　１本
- M2.6×9.7 鍋ネジ　４本
- M2.6×19.7 鍋ネジ　３本
- M2.6×8 六角ネジ　３本
- M2.6×15.9 六角ネジ　１本
- M2.6×10 六角ネジ　１本
- M2.6×12 皿ネジ　１本
- M2×19.7 段付き鍋ネジ　１本
- M2×8 六角ネジ　１本

上記のネジは以下のネジボックスに保管している。
<img src="https://github.com/open-rdc/office_robot/assets/71181654/f5dca2a6-71c0-4886-ac1a-75cb6f931592" width="300" height="300">


## サーボ（アームに取り付けられているのを含む）
- 合計15個
  - B3M 1170 4個
  - B3M 1040 11個

※頭などに取り付けられいる段ボール外のサーボはまだ数えていない

## サーボケーブル
- 450mm　10本
## RS485/USBシリアル変換アダプター
- 合計３個
  - 電源ケーブル接続済み　２個
  - 電源ケーブル未接続　１個
<img src="https://github.com/open-rdc/office_robot/assets/71181654/e794d5e6-028d-412d-a367-8693c5c2a95d" width="300" height="300">

※発見してからまだ通電及び検証はしていない。

## ギア
ギア　１個
<img src ="https://github.com/open-rdc/office_robot/assets/71181654/0fd095a8-c909-4e21-90bf-f6c886740a36" width ="300" height = "300">

## 3D プリントパーツ
- 6個
- 形状それぞれバラバラ
<img src ="https://github.com/open-rdc/office_robot/assets/71181654/b7f60b8b-c266-4e47-92f9-c3db1d317c01" width ="300" height="300">

<img src ="https://github.com/open-rdc/office_robot/assets/71181654/0745c3a2-93d2-4534-ba6e-f68f3e0d1ba4" width ="300" height ="300">

## CAD図にない切削パーツ(T5)
- 合計４個
  - 真ん中に穴が開いてる物　２個
  - 真ん中に穴が開いていない物　２個
<img src ="https://github.com/open-rdc/office_robot/assets/71181654/8c17e0f9-527b-4841-9d8e-89a313de4078" width ="300" height ="300">

## 手先カメラ
- md-4010l-nu　２個
※使えるかの検証を行っていない
<img src ="https://github.com/open-rdc/office_robot/assets/71181654/a33aab6d-50ee-4fae-add9-dddad49e16ac" width="300" height ="300">

**Comment by MibuchiYuta** [comment]
@Keita1Mori @KiyoshiroKawanabe 必要がなければcloseしてください

**Comment by Keita1Mori** [comment]
新たに設計する際にこのissueをreopenする
