### ISSUE TITLE
インストールと実行方法（テンポラリ）

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_or#20]
インストールと実行方法を記録する

**Comment by yasuohayashibara** [comment]
インストール

### Install
Precondition:  
1) Install ROS noetic (Ubuntu20.04/docker)  
2) Install [python3-catkin-tools](https://github.com/open-rdc/orne-box/issues/79#issuecomment-1818041979)  

navigation
```
cd ~/catkin_ws/src
git clone https://github.com/open-rdc/office_robot
wstool init
wstool merge office_robot/rdc_navigation/orne_box_pkgs.install
wstool up
rosdep install --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
cd ~/catkin_ws
catkin build
source ~/.bashrc
```

### Excecution

On simulator (gazebo)  
```
roslaunch orne_box_bringup orne_box_sim.launch
roslaunch orne_box_navigation_executor nav_static_map.launch
```

**Comment by yasuohayashibara** [comment]
manipulation
```
cd ~/catkin_ws/src
wstool merge office_robot/rdc_manipulation/rdc_manipulation_pkgs.install
wstool up
rosdep install --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
catkin build
source ~/.bashrc
```

Execution
Simulator
```
roslaunch cit_gazebo cit_mani.launch
roslaunch cit_moveit_config moveit_planner.launch
```
Real Robot (only left arm)
```
roslaunch manipulator_driver manipulator_driver_left_arm.launch
roslaunch manipulator_driver manipulator_controller_left_arm.launch
roslaunch cit_moveit_config moveit_planner.launch
```

**Comment by yasuohayashibara** [comment]
manipulationの様子
meshがrvizで表示できないので代わりにtfを表示
(wslで開発をしているが，wslでなければ表示されるようです)

[![IMAGE](http://img.youtube.com/vi/fttdPRcElDg/0.jpg)](https://youtu.be/fttdPRcElDg)

**Comment by yasuohayashibara** [comment]
地図を作ったり自律移動させたりする方法
（ノードの読み替えが必要になります．）

https://github.com/open-rdc/orne_navigation/wiki/ORNE%E7%92%B0%E5%A2%83%E5%8B%95%E4%BD%9C%E3%81%AE%E6%89%8B%E9%A0%86

**Comment by MibuchiYuta** [comment]
# 実ロボットの環境構築

## 1. デバイスの有効化
上記の環境を構築したノートPCをロボットに載せる。USBでモータドライバと、イーサネットでLiDARと接続する。

### モータドライバのセットアップ
```
cd ~/catkin_ws/src/icart_mini/icart_mini_setup/config/
```

70-sensors.rulesを以下のように書き換える
```
SUBSYSTEMS=="usb", KERNEL=="ttyACM[0-9]", ACTION=="add", ATTRS{idVendor}=="15d1", ATTRS{idProduct}=="0000", PROGRAM="/opt/ros/noetic/env.sh rosrun urg_node getID %N q", MODE="666", SYMLINK+="sensors/hokuyo_$result", GROUP="dialout"
SUBSYSTEMS=="usb", KERNEL=="ttyACM*", ACTION=="add", ATTRS{product}==" AT91SAM CDC Demo Application", MODE="666", SYMLINK+="sensors/icart-mini", GROUP="dialout"
SUBSYSTEMS=="usb", KERNEL=="ttyUSB*", ACTION=="add", ATTRS{product}=="FT232R USB UART", MODE="666", SYMLINK+="sensors/imu", GROUP="dialout"
SUBSYSTEMS=="usb", KERNEL=="ttyACM*", ACTION=="add", ATTRS{idVendor}=="2341", ATTRS{idProduct}=="0043", MODE="666", SYMLINK+="sensors/imu", GROUP="dialout"
SUBSYSTEMS=="usb", KERNEL=="ttyACM*", ACTION=="add", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="ffee", MODE="666", SYMLINK+="sensors/imu16465", GROUP="dialout"
SUBSYSTEMS=="usb", KERNEL=="ttyACM*", ACTION=="add", ATTRS{idVendor}=="1546", ATTRS{idProduct}=="01a8", MODE="666", SYMLINK+="sensors/gnss", GROUP="dialout"
```

スクリプトを実行する
```
cd ../scripts
./create_udev_rules
```
モータドライバが認識されていることを確認する
```
ls /dev/sensors
```
icart-miniがあれば良い

### LiDARのセットアップ

使用するLiDARのIPアドレスは192.168.0.1とする

設定アプリのネットワークタブを開く
有線の表記があることを確認し、右側の+ボタンからプロファイルを追加する

ipv4タブのipv4メソッドを手動に変更する
アドレス　192.168.0.103
ネットマスク 24
ゲートウェイ 192.168.0.1

ipv6タブに移動し、ipv6メソッドを無効にする

適用を押してプロファイルの設定を完了する。

**Comment by yasuohayashibara** [comment]
新しいコミットでは以下のように修正しました．
`/opt/ros/melodic/env.sh -> /opt/ros/noetic/env.sh`

https://github.com/open-rdc/icart/blob/b2f723598e070dcabcd17dfcc784e6e5b7d5ea53/icart_mini_setup/config/70-sensors.rules#L1

あと，他に修正箇所があればレポジトリの方を更新しますのでご指摘ください．

なお，現在のロボットのLiDARはイーサーネットで接続するタイプですので，上記の修正は影響を受けません．

**Comment by KiyoshiroKawanabe** [comment]
2月4日に作業した際、LiDARとの通信ができませんでした。
以下の修正を加え通信ができるようになりましたので、上記[LiDARのセットアップ](https://github.com/open-rdc/office_robot/issues/20#issuecomment-1923244686)に追記します。
orne_box.launchで指定しているLiDARのIPアドレスを書き換える必要がありました。[コミットID](https://github.com/open-rdc/office_robot/commit/ec75fa395b353af20091921f36f5c38d795460d7)
同様に、icart_mini_draiverのほうでもIPアドレスをLiDARのIPアドレスに書き換える必要があります。

**Comment by yasuohayashibara** [comment]
orne_orでのインストール及び実行方法

インストール

### Install
Precondition:  
1) Install ROS noetic (Ubuntu20.04/docker)  
2) Install [python3-catkin-tools](https://github.com/open-rdc/orne-box/issues/79#issuecomment-1818041979)  

navigation
```
cd ~/catkin_ws/src
git clone https://github.com/open-rdc/office_robot
wstool init
wstool merge office_robot/orne_or_navigation/orne_or_pkgs.install
wstool up
rosdep install --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
cd ~/catkin_ws
catkin build
source ~/.bashrc
```

### Excecution

On simulator (gazebo)  
```
roslaunch orne_or_bringup orne_or_sim.launch
roslaunch orne_or_navigation_executor nav_static_map.launch
```

**Comment by yasuohayashibara** [comment]
orne_orでのインストール及び実行方法

manipulation
```
rosdep install --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
catkin build
source ~/.bashrc
```

Execution
Simulator
```
roslaunch cit_gazebo cit_mani.launch
roslaunch orne_or_moveit_config moveit_planner.launch
```
Real Robot (only left arm)
```
roslaunch manipulator_driver manipulator_driver_left_arm.launch
roslaunch manipulator_driver manipulator_controller_left_arm.launch
roslaunch orne_or_moveit_config moveit_planner.launch
```

**Comment by yasuohayashibara** [comment]
READMEに転載したので，issueを閉じます．
