### ISSUE TITLE
ロボットアームの初期位置の変更

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_or#21]
gazeboのシミュレータに合わせて，実ロボットの関節の角度を取り付け直す．

![image](https://github.com/open-rdc/office_robot/assets/5755200/22f70596-d6fe-4e07-953f-30ddb2730de6)

**Comment by Keita1Mori** [comment]
# 作業
gazeboのシミュレータに合わせて、実ロボットの関節角度を取り付け直しました。
## 作業者:左腕(森)、右腕(川鍋)

下記完了時の写真
<img src ="https://github.com/open-rdc/office_robot/assets/71181654/951638e4-c1ac-476b-86db-237dd3004f60" width = "500" hight = "500">
<img src = "https://github.com/open-rdc/office_robot/assets/71181654/7e0f8996-b5e8-49f1-b4ec-4fb44c2202cc" width = "500" hight = "500">
<img src = "https://github.com/open-rdc/office_robot/assets/71181654/3d14d002-e16a-4167-b7db-3a2e595d8b80" width = "500" hight = "500">
<img src = "https://github.com/open-rdc/office_robot/assets/71181654/9744169b-153c-43de-9675-a093d34e9d3b" width = "500" hight = "500">

## 以下のサーボのcenter positionを変更
### 右腕
- 肩ピッチ(ID:11) 15000⇒-11232
- 肩ヨー(ID:12) 6000⇒9000
- 肘ヨー(ID:13) 17000⇒18000
- 手首ロール(ID:16) 5000⇒4500

### 左腕
- 肘ヨー(ID:23) 0⇒-900
- 手首ピッチ(ID:25) 0⇒-15785
- 手首ロール(ID:26) 0⇒-4713

**Comment by Keita1Mori** [comment]
鉛蓄電池での確認を終えてからこのissueをcloseする

**Comment by Keita1Mori** [comment]
#31 に表示されている動画のように鉛蓄電池によって動作確認を終えた。しかし肩ピッチ(ID:21)の初期位置がおよそ90度回転していた。原因として、ピッチギアを回しすぎるとギアがかみ合わなくなることが考えられる。解決策として初期位置の状態が分かるように印をつけるようにする。

**Comment by yasuohayashibara** [comment]
#32 にも記載した内容になりますが，サーボに個別の設定をする場合は，一覧を作成したほうが良いと思います．
複数のissueに渡って個別に記載していくと，結局どれが正解か分からなくなります．
あと，起動時の上書きしているパラメータもありそうですのでご注意ください．

**Comment by KiyoshiroKawanabe** [comment]
肩ピッチギアに印をつけました。ギアが外れて初期位置がずれることが多々あるので、初期位置がずれている場合は印の位置からかみ合わせてください。
### 左
![IMG_2664](https://github.com/open-rdc/orne_or/assets/53420739/36be788c-6c3c-4daf-9b79-28c8652057e1)
### 右
![IMG_2663](https://github.com/open-rdc/orne_or/assets/53420739/f03c81db-7ee2-4296-9c77-a2df8054acc9)

**Comment by Keita1Mori** [comment]
対応したので、issueをcloseします。
