### ISSUE TITLE
アームの関節角度の制限とトルクの制限の入力

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_or#22]
以下のようにURDFファイルにアームの関節角度とトルクの制限を入力するようになっているので，実ロボットにあわせてパラメータを変更する．

https://github.com/open-rdc/office_robot/blob/0de5121ec7b2284bf2f6032c203eaa540337b438/rdc_manipulation/cit_description/urdf/manipulator.urdf#L114

**Comment by MibuchiYuta** [comment]
実ロボットのB3Mのパラメータを[wiki](https://github.com/open-rdc/orne_or/wiki/B3M%E3%81%AE%E3%83%91%E3%83%A9%E3%83%A1%E3%83%BC%E3%82%BF%E4%B8%80%E8%A6%A7)にまとめました

**Comment by MibuchiYuta** [comment]
サーボゲインもまとめる必要がある

**Comment by MibuchiYuta** [comment]
角度制限に関しては、B3M側の設定でセンターポジションを0にし、出力ホーンの固定位置を変えることで対応させる

**Comment by MibuchiYuta** [comment]
発熱を抑えるため、Kiゲインを後日0に変更する

**Comment by KiyoshiroKawanabe** [comment]
アームに使用しているすべてのサーボモータのCentor Pointを0にして初期位置を調整した。
以下にサーボそれぞれのゲインと角度Max,Minを示す。
| ID | Kp | Kd | Ki | Static<br>Friction | Dynamic<br>Friction | Min | Max |
|  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |
| 11 | 42000 | 400 | 1000 | 0 | 0 | -32000 | 32000 |
| 12 | 42000 | 400 | 1000 | 0 | 0 | -9000 | 9000 |
| 13 | 35000 | 500 | 1800 | 0 | 0 | -4000 |17000 |
| 14 | 35000 | 500 | 1800 | 0 | 0 | -11000 | 11000 |
| 15 | 35000 | 500 | 1800 | 0 | 0 | -11000 | 11000 |
| 16 | 35000 | 500 | 1800 | 0 | 0 | -32000 | 32000 |
| 17 | 35000 | 500 | 1800 | 0 | 0 | -17000 | 1990 |
| 21 | 42000 | 400 | 1000 | 0 | 0 | -32000 | 32000 |
| 22 | 42000 | 400 | 1000 | 0 | 0 | -9000 | 9000 |
| 23 | 35000 | 500 | 1800 | 0 | 0 | -4000 | 17000 |
| 24 | 35000 | 500 | 1800 | 0 | 0 | -11000 | 11000 |
| 25 | 35000 | 500 | 1800 | 0 | 0 | -11000 | 11000 |
| 26 | 35000 | 500 | 1800 | 0 | 0 | -32000 | 32000 |
| 27 | 35000 | 500 | 1800 | 0 | 0 | 0 | 10000 |

**Comment by KiyoshiroKawanabe** [comment]
@MibuchiYuta 出力トルクはどうする？B3Mの最大トルク？

**Comment by KiyoshiroKawanabe** [comment]
URDFに、可動域の入力をしました。https://github.com/open-rdc/orne_or/commit/d1fd87f6bc5464e6bd3887ad21d424288fd153d9

**Comment by MibuchiYuta** [comment]
本日実ロボットで動作させたところ、r_elbow_roll_link(id:23)が+170°まで移動しませんでした。サーボ側の角度制限が間違っている可能性があるため確認します。

**Comment by MibuchiYuta** [comment]
> [@MibuchiYuta](https://github.com/MibuchiYuta) 出力トルクはどうする？B3Mの最大トルク？

[B3M software manual](https://kondo-robot.com/w/wp-content/uploads/B3M_SoftwareManual1.2.0.3.pdf)のp7にスペック表がありますが最大トルクではなく最大連続トルクを参照するのがよさそうです。

**Comment by yasuohayashibara** [comment]
最大連続トルクの方が良いと思います．

**Comment by KiyoshiroKawanabe** [comment]
> 本日実ロボットで動作させたところ、r_elbow_roll_link(id:23)が+170°まで移動しませんでした。サーボ側の角度制限が間違っている可能性があるため確認します。

確認しましたが、B3M側の制限は問題無さそうです。
<img src="https://github.com/open-rdc/orne_or/assets/53420739/0914a1f9-87e4-4ff1-b9b2-7a2008733190" width="600">

**Comment by KiyoshiroKawanabe** [comment]
アームの全てのサーボモータのKiゲインを0に変更しました。

**Comment by MibuchiYuta** [comment]
> 本日実ロボットで動作させたところ、r_elbow_roll_link(id:23)が+170°まで移動しませんでした。サーボ側の角度制限が間違っている可能性があるため確認します。

B3Mマネージャーから直接角度を指定して動かしたところ170°までしっかり動作したため、モータに問題はなさそうです。

**Comment by MibuchiYuta** [comment]
関節角度の制限ですが、driverのconfig側でも記述されていました。どうやらそれが影響していたようです。
https://github.com/open-rdc/orne_or/blob/5f0fd952b46418eb3f8d88e94408ad97bb72babd/orne_or_manipulation/orne_or_manipulator_driver/config/cit_driver.yaml#L23-L31

修正したところ、シミュレータと同じ角度まで動作しました。

**Comment by KiyoshiroKawanabe** [comment]
URDFのeffortに最大連続トルクを記入しました。https://github.com/open-rdc/orne_or/commit/2ca176ffed8316d8e3633d20789e49a1ede2cb9c

URDF上でのアームの関節角度とトルクの制限は入力し終えたのでissueを閉じます。
