### ISSUE TITLE
台車のURDFの作成

### ISSUE THREAD

**Issue by KiyoshiroKawanabe** [open-rdc/orne_or#23]
# URDF作成のために必要な数値
- 台車の車輪間距離
- 車輪の直径

**Comment by KiyoshiroKawanabe** [comment]
駆動輪の車輪間距離：**303mm**
<img src="https://github.com/open-rdc/office_robot/assets/53420739/2b9e3028-b8f1-479b-986e-31b67191d74d" width=450>
<img src="https://github.com/open-rdc/office_robot/assets/53420739/ffe821b1-1464-405c-b208-8d71383214a8" width=450>

**Comment by KiyoshiroKawanabe** [comment]
車輪直径**150mm**
<img src="https://github.com/open-rdc/office_robot/assets/53420739/f109e1a5-b1dd-42bb-8714-c3eb700ad711" width=400>

**Comment by MibuchiYuta** [comment]
#25 でその後の作業の報告をしています
