### ISSUE TITLE
GazeboのロボットアームのIDと実ロボットのアームのIDが一致しているかをチェック

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_or#24]

**Comment by yasuohayashibara** [comment]
こちらに記載されています．
kondo_driverは使用しません．

https://github.com/open-rdc/office_robot/blob/noetic-devel/rdc_manipulation/manipulator_driver/config/cit_driver.yaml

**Comment by MibuchiYuta** [comment]
現在左腕はmove itを用いて動作しており、目立って関節の動きが違うなどはありません。右腕を今後動かし、確認します。

**Comment by MibuchiYuta** [comment]
右腕を動作させましたが、サーボの角度制限等によりチェックができなかったため問題を解決し次第再度確認します。

**Comment by Keita1Mori** [comment]
https://github.com/KiyoshiroKawanabe/OfficeRobot-Hardware/issues/10
にてサーボIDの振り分けについて記録している

**Comment by yasuohayashibara** [comment]
以下頻繁に参照しなければならないデータだと思いますので，READMEに転記しました．

https://github.com/open-rdc/orne_or/blob/noetic-devel/README.md

**Comment by Keita1Mori** [comment]
上記の画像が前のものだったので、今使われているサーボIDの画像に変更しました。
https://github.com/open-rdc/orne_or/blob/noetic-devel/README.md

**Comment by KiyoshiroKawanabe** [comment]
以下にサーボそれぞれのゲインと角度Max,Minを示す。
| ID | Kp | Kd | Ki | Static Friction | Dynamic Friction | Max | Min |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 11 | 42000 | 400 | 1000 | 0 | 0 | Max | Min |
| 12 | 42000 | 400 | 1000 | 0 | 0 | Max | Min |
| 13 | 35000 | 500 | 1800 | 0 | 0 | Max | Min |
| 14 | 35000 | 500 | 1800 | 0 | 0 | Max | Min |
| 15 | 35000 | 500 | 1800 | 0 | 0 | Max | Min |
| 16 | 35000 | 500 | 1800 | 0 | 0 | Max | Min |
| 17 | 35000 | 500 | 1800 | 0 | 0 | Max | Min |

**Comment by KiyoshiroKawanabe** [comment]
アームに使用しているすべてのサーボモータのCentor Positionを0にして初期位置を調整しました。

**Comment by MibuchiYuta** [comment]
実ロボットで確認を行い、スライダー,首以外のサーボのIDがあっていることを確認しました。
