### ISSUE TITLE
ロボット走行部のサイズと位置の入力

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_or#25]
ロボットの走行部のサイズと位置を入力することが必要

**Comment by yasuohayashibara** [comment]
ロボットのベースの中心位置とサイズ

https://github.com/open-rdc/office_robot/blob/9a06b503bd4be7b2a4c59f374bf520dbcca7aaa5/rdc_navigation/orne_box_description/urdf/orne_box.urdf.xacro#L9-L12

車輪の中心位置
https://github.com/open-rdc/office_robot/blob/9a06b503bd4be7b2a4c59f374bf520dbcca7aaa5/rdc_navigation/orne_box_description/urdf/orne_box.urdf.xacro#L25

車輪のサイズ
https://github.com/open-rdc/office_robot/blob/9a06b503bd4be7b2a4c59f374bf520dbcca7aaa5/rdc_navigation/orne_box_description/urdf/orne_box.urdf.xacro#L34

LiDARの位置
https://github.com/open-rdc/office_robot/blob/9a06b503bd4be7b2a4c59f374bf520dbcca7aaa5/rdc_navigation/orne_box_description/urdf/orne_box.urdf.xacro#L138

**Comment by yasuohayashibara** [comment]
#23 にあった数値を入れてロボットを描きました．
コミットしてあります．
このように実際のロボットに近づくように数値を入れてみてください．

干渉があまり気にならないのであれば，ボディのサイズはあまり気にしなくても良いです．
LiDARの位置は自己位置推定にとって重要ですので，できるだけ正確な値を入れたほうが良いです．
ちなみに，実ロボットのLiDARの取り付け角度はこだわったほうが良いです．
少しの角度のずれでも10m先では大きなずれになります．

![image](https://github.com/open-rdc/office_robot/assets/5755200/393af260-44c2-4889-9bf5-0d3ded31e884)

**Comment by KiyoshiroKawanabe** [comment]
URDFを変更しました。
cartographerで使用した、xacroファイルからurdfファイルに書き換えたものもコミットしました。https://github.com/open-rdc/office_robot/commit/ac09380ba7244da81e78ddc3be778c005188ddfa

**Comment by KiyoshiroKawanabe** [comment]
![Screenshot from 2024-02-07 16-38-03](https://github.com/open-rdc/office_robot/assets/53420739/962debe6-ef03-4b07-b70c-4c1509507b12)
