### ISSUE TITLE
icart miniのハードウェアと通信できない

### ISSUE THREAD

**Issue by KiyoshiroKawanabe** [open-rdc/orne_or#26]
pcとicart miniをUSB接続をしているが、認識できない

**Comment by KiyoshiroKawanabe** [comment]
詳細は不明ですが、
```rosrun orne_box_setup create_udev_rules```
を実行したら、デバイスを抜き差ししても
```ls /dev/sensors```
でicart_miniを確認できるようになったので一旦こちらのissueを閉じます。

**Comment by KiyoshiroKawanabe** [comment]
詳細は不明ですが、
```$ rosrun orne_box_setup create_udev_rules```
を実行したら、デバイスを抜き差ししても
```$ ls /dev/sensors```
でicart_miniを確認できるようになったので一旦こちらのissueを閉じます。

**Comment by yasuohayashibara** [comment]
金曜日は色々をシステムを変更しすぎて，udev ruleが正常に機能しなくなっていたのだと思います．
