### ISSUE TITLE
台車が振動的

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_or#27]
移動用モータのフィードバックゲインが高いせいか動きがやや振動的

以下のファイルのパラメータを変更する
https://github.com/open-rdc/office_robot/blob/noetic-devel/rdc_navigation/orne_box_setup/config/orne_box.param

パラメータファイルの決定法
https://www.roboken.iit.tsukuba.ac.jp/platform/wiki/yp-spur/parameter-file

**Comment by KiyoshiroKawanabe** [comment]
パラメータを変更し、ジョイスティックで動かしました。変更したパラメータで振動をしないことを確認しました。
https://drive.google.com/file/d/1Dr1ELczcesjTnTfvoR8PoioOcz4YN1Va/view?usp=sharing

変更箇所→https://github.com/open-rdc/office_robot/commit/3ee7387b247b7c189a50a956a2c342a2d8db0e69

**Comment by yasuohayashibara** [comment]
以下ですが，最大トルクを下げた理由を教えてください．
あと，以下は何を示すパラメータかを教えてください．

TORQUE_LIMIT

この数値を変更するとおそらくモータの最大トルクが小さくなるので，坂道を移動するときなどに問題になるおそれが高いです．
意図的に行っている場合は良いですが，坂道を登れなくてモータのトルクが足りないという事態に陥ったときにこのパラメータの存在を知らないといらぬ遠回りをすることになります．
パラメータを変更するときには最小限にとどめたほうが良いと思います．

あと，ゲインを下げていますが，みなさんも御存知の通りこれによって誤差が増大しますので，目標経路に沿って走行しなくなります．
できるだけ調整方法に記載してある方法で調整したほうが良いです．
ヒューマノイドロボットで経験していると思いますが，サーボのゲインを変えると全てのパラメータを再設定することになります．
結局，こちらもいらぬ遠回りをすることになるかもしれませんので，慎重に決定したほうが良いパラメータとなります．

https://github.com/open-rdc/office_robot/blob/ec75fa395b353af20091921f36f5c38d795460d7/rdc_navigation/orne_box_setup/config/orne_box.param#L13-L14

**Comment by KiyoshiroKawanabe** [comment]
林原先生から教えていただいた[こちらのサイト](https://www.roboken.iit.tsukuba.ac.jp/platform/wiki/yp-spur/parameter-file)を参考に、下記パラメータを修正しました。https://github.com/open-rdc/office_robot/commit/d84fa7ae3759413317efe6a785eb16838f4b4c80
- MOTOR_VC
- TORQUE_NEWTON
- TORQUE_VISCOS
- INTEGRAL_MAX
- TORQUE_MAX
- GAIN_KP
- GAIN_KI
- MASS

テレオペで走行させ発振しないことを確認しました。
また、走行時(特に前進から停止に移るとき)に鈍い振動音がしますが、キャスターの異音であると確認しました。

**Comment by KiyoshiroKawanabe** [comment]
走行中に少ない頻度で発振が確認できたため、KIゲインの調整をしました。https://github.com/open-rdc/office_robot/commit/f1979568617087e38fc6281aabe0e22856d608ee
2月7日に地図作りのため、津田沼キャンパスを走行させましたが、発振は見られませんでした。
また、以前に踏破できなかった段差などを乗り越えられることを確認しました。
