### ISSUE TITLE
地図の作成

### ISSUE THREAD

**Issue by KiyoshiroKawanabe** [open-rdc/orne_or#29]
地図の作成をする手順をまとめる。
今回の作成には、cartographerを使用して行う。
# cartographerのインストール
[こちらのサイト](https://qiita.com/porizou1/items/c2cb0765bc60caa3f755)の手順通りにROSにcartographer_rosをインストールする。
# rosbagの収集
以下コマンドを実行し、テレオペで走行させrosbagを収集する。filenameは任意の名前。
```$ cd ~/rosbag```
```$ rosbag record -a -O failname```
地図作成の際に使用するtopicは、scanとicart_mini/odomを使用するため以下コマンドでもよい
```$ rosbag record /scan /icart_mini/odom -O failename```

# cartographerの実行
```$ roslaunch cartographer_ros demo_backpack_2d.launch bag_filename:=${HOME}/rosbag/filename.bag```

# 地図の保存
下記コマンドで地図を保存する
-fを付けずに、現在いるディレクトリに保存することも可能。今回は以下のディレクトリを指定して保存。mapnameは任意の名前。
```$ rosrun map_server map_saver -f /home/officerobot/catkin_ws/src/office_robot/rdc_navigation/orne_box_navigation_executor/maps/mapname```

**Comment by KiyoshiroKawanabe** [comment]
使用しているpcでは、```$ rosrun map_server map_saver```では地図の保存ができない。(スペック不足だと思われる。)
以下コマンドを使用することで地図の作成と保存が可能であることを確認した。
```$ roslaunch cartographer_ros assets_writer_backpack_2d.launch bag_filename:=${HOME}/rosbag/filename.bag```

**Comment by yasuohayashibara** [comment]
メモリが足りない場合は，ubuntuのswapを大きくすると地図が作れます．
私はwslで使用しているので，wslの設定を変えると地図が生成できるようになります．

**Comment by yasuohayashibara** [comment]
以前作成したcartographerのレポジトリ
https://github.com/open-rdc/cartographer_ros
