### ISSUE TITLE
必要なパーツ

### ISSUE THREAD

**Issue by Keita1Mori** [open-rdc/orne_or#3]

**Comment by Keita1Mori** [comment]
# 左腕（お茶を持ってる方）
- 0.75_120_S75B120A-0351 ×1
<img width="300" alt="スクリーンショット 2023-09-22 211410" src="https://github.com/open-rdc/office_robot/assets/71181654/cc6ca75c-0c1e-4a16-b460-d51a112b10ea">

【加工】穴あけ

---

- 0.75_30_S75B30B+0306 ×1
<img width="280" alt="スクリーンショット 2023-09-22 211728" src="https://github.com/open-rdc/office_robot/assets/71181654/e6fd5a36-55d7-4402-96c0-85fb7ee26eec">

【加工】穴あけ

---

- スラスト高さ位置調整 ×1
<img width="456" alt="スクリーンショット 2023-09-22 211954" src="https://github.com/open-rdc/office_robot/assets/71181654/fca365a1-0c88-4b15-8b9f-411009e51b7d">

【加工】POM, 切削

---

- washer_BA3047 ×1
※段ボールの中にいくつかあるけど傷及び汚れがついている
<img width="254" alt="スクリーンショット 2023-09-22 212750" src="https://github.com/open-rdc/office_robot/assets/71181654/8faea5e1-ba37-4e7c-82f5-f0ef81f83eb3">

---

- D5060-0550 ×1
<img width="296" alt="スクリーンショット 2023-09-22 213143" src="https://github.com/open-rdc/office_robot/assets/71181654/e55876af-e4a5-48db-87ae-bcfe849eb329">

---

- FL606ZZ ×1
<img width="275" alt="スクリーンショット 2023-09-22 213410" src="https://github.com/open-rdc/office_robot/assets/71181654/7d3186ce-d2e8-4016-b243-e64c9e89ed57">

---

- ギア_サーボ接続フレーム(T2.5)×1
<img width="439" alt="スクリーンショット 2023-09-22 213550" src="https://github.com/open-rdc/office_robot/assets/71181654/ca78d1f3-7c4a-416d-9468-cc2b606a22e9">

【加工】A2017, 切削

---

- ヨー_ヨー_接続フレーム_2_151207修正品（コの字型) (T2)×1
<img width="447" alt="スクリーンショット 2023-09-22 214155" src="https://github.com/open-rdc/office_robot/assets/71181654/1a2267a4-9099-40d2-9c8c-8e174636ff55">

サーボブラケットB【B3M-1000シリーズ用】（2セット入り）

**Comment by Keita1Mori** [comment]
# 右腕
## パーツ
- ヨー_ヨー_接続フレーム_151207修正品(T2)×１
<img width="300" alt="スクリーンショット 2023-09-23 013313" src="https://github.com/open-rdc/office_robot/assets/71181654/7a701f96-331f-4b74-80f6-184fc7f4a100">

【加工】A5052，切削，曲げ

---

- ヨー_ヨー_接続フレーム_151207修正品(T2)(コの字）×2
<img width="300" alt="スクリーンショット 2023-09-23 013725" src="https://github.com/open-rdc/office_robot/assets/71181654/fc1bc9f3-3f1f-4a8d-ba1a-0ce565a8cceb">

サーボブラケットB【B3M-1000シリーズ用】（2セット入り）

---

## ネジ
- 六角ネジ　M3×5 8本
- 鍋ネジ　M2.6×14　4本
- 鍋ネジ　M2.6×16　4本
- 六角ネジ　M2.6×５　18本
- 皿ネジ　M2.6×５　3本

**Comment by MibuchiYuta** [comment]
@Keita1Mori @KiyoshiroKawanabe 必要がなければcloseしてください

**Comment by Keita1Mori** [comment]
オフィスロボットの復元が完了したので、こちらのissueをcloseします。
