### ISSUE TITLE
故障した電子回路の調査

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/orne_or#30]
モータドライバに5Vの供給をすると、通常ではUSBでのPCとの通信などができる。
しかし、現在通信はできず、24Vのモータ用の電源も供給するとUSBでのPCとの通信ができるようになる。この問題を調査し修理を行いたい。

**Comment by yasuohayashibara** [comment]
モータドライバのマニュアル
https://t-frog.com/products/motor_driver/files/TF-2MD3-R6_Manual_rev5.pdf

**Comment by MibuchiYuta** [comment]
トラブルシューティング
https://t-frog.com/products/motor_driver/troubleshooting.php

**Comment by MibuchiYuta** [comment]
トラブルシューティングに沿って非通電時のjs1の導通を確認したところ、js1の両端は非道通でしたのでL1が破損しているようです。
![IMG_1045](https://github.com/open-rdc/office_robot/assets/53966307/689a93f9-43de-4968-9d88-47b08f4fd2b1)
![IMG_1043 (1)](https://github.com/open-rdc/office_robot/assets/53966307/82b4c7b9-cfdc-4584-8090-083e833e943f)

**Comment by yasuohayashibara** [comment]
修理可能かどうかの問い合わせをしました．

**Comment by MibuchiYuta** [comment]
今後のことを考え対象の交換パーツの型番を調べる

**Comment by MibuchiYuta** [comment]
モータのパラメータを見直す必要があるかもしれない
https://github.com/open-rdc/orne_or/issues/27

**Comment by MibuchiYuta** [comment]
orne_boxのパラメータを参考に上記issueの作業をやり直す

**Comment by MibuchiYuta** [comment]
- 適正なコンデンサを選定しているか調べる
- 使用しているコンデンサの容量を計測する

**Comment by MibuchiYuta** [comment]
こちらのマルチメータを使います
https://www.sanwa-meter.co.jp/japan/pdf/manual/digital_multimeters/PM3_JP.pdf

**Comment by Keita1Mori** [comment]
走行部モータの型番
TF-M30-24-3500-G15L/R
ウェブサイト:https://t-frog.com/products/motor/

**Comment by MibuchiYuta** [comment]
マニュアルから算出したところ使用しているモータに対して1000μFのコンデンサを使用しているのは適切でした。

**Comment by MibuchiYuta** [comment]
回路をロボットに戻し、テレオペで走行できることを確認しました
