### ISSUE TITLE
  MoveIt上での動作と実ロボットの動きが違う問題

### ISSUE THREAD

**Issue by KiyoshiroKawanabe** [open-rdc/orne_or#32]

**Comment by KiyoshiroKawanabe** [comment]
```
roslaunch manipulator_driver manipulator_driver_left_arm.launch
roslaunch manipulator_driver manipulator_controller_left_arm.launch
roslaunch cit_moveit_config moveit_planner.launch
```
上記コマンドを実行し、MoveItでアームの姿勢を決め実ロボットのサーボにそれぞれ角度を送る。
以下、現状確認できている問題点
- ~ID23が指定角度の半分程度しか回転しない~ 解決
- ~ID25が反対に回転する~ 解決
- ID23とID24が他のサーボモータと比べて発熱している
- 動作するときに振動している

**Comment by KiyoshiroKawanabe** [comment]
> ID23が指定角度の半分程度しか回転しない

B3M Managerで確認したところ、角度制限（0-5000）がかかっていた。
角度制限を肘を曲げても干渉しない、−3000-17000に書き換えて解決した。

> ID24が反対に回転する

取付時に出力とフリーを反対につけている可能性が高い。
B3M Managerでreversモードにして対処した。特に問題がなければ、付け替える必要はないと考える。

**Comment by yasuohayashibara** [comment]
パラメータを標準の値から変える場合は，どこかに一覧表を作成して管理したほうが良いと思います．

**Comment by MibuchiYuta** [comment]
ID23の肘ヨー軸の発熱に関しては旧ロボット開発時に酷使していた可能性が高いのが理由ではないかとのことです

**Comment by MibuchiYuta** [comment]
> 取付時に出力とフリーを反対につけている可能性が高い。
>B3M Managerでreversモードにして対処した。特に問題がなければ、付け替える必要はないと考える。  

こちらはCADデータと共に上下判定して取り替えることで確認する。

**Comment by KiyoshiroKawanabe** [comment]
取り付け位置が反転していたID24のサーボモータを取り付けなおした。
B3M Managerでreversモードにしていたものを解除したが、動作時に反対に回転することを確認した。
試しにreversモードを有効にして試したが、その際も反対に回転していたためpcの再起動とusbの抜き差しを行い再度試した。
``` $ roslaunch manipulator_driver manipulator_driver_left_arm.launch  ```
を実行したところ、以下のエラーがでた。
``` [ERROR] [1707886395.678951641]: Could not init B3M: ERROR: b3m_init: Get serial port parameters ```
/dev/ttyUSB0がないからではないかと考える。
USBを一度抜いて10秒以経ってから差し込んで実行したが、同じエラーがでた。

ls /dev/tty*で表示されるなかに、ttyUSB0が表示されない。
lsusbでは、Kondo Kagaku RS485 USB/Serial Converterが表示される。

**Comment by Keita1Mori** [comment]
上記のttyUSB0が表示されない問題は解決しました。https://github.com/open-rdc/orne_or/issues/39

**Comment by MibuchiYuta** [comment]
#42 で減速が反映されていない問題に取り組んでいます。

**Comment by MibuchiYuta** [comment]
エンドエフェクタを含め実ロボットの動きは一緒になったためcloseします
