### ISSUE TITLE
現在のマニピュレータ用のシミュレータ環境に問題がないかを確認する

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/orne_or#38]
空のペットボトルを持ち上げる動作ができるか確認する

**Comment by MibuchiYuta** [comment]
メンバーの個人のPCでどのくらい動くか録画をして記録したい。

**Comment by Keita1Mori** [comment]
以下の動画では森のPCでUbuntu 20.04ネイティブで動かした際の動画です。
https://youtu.be/SXsyyrC3G68

**Comment by yasuohayashibara** [comment]
@Keita1Mori 
実習に際して問題ないと考えてよいですか？

**Comment by Keita1Mori** [comment]
動画で示したように左右のshoulder_rollを後ろに持ってくる際にright_shoulder_rollは-90°に対し、left_shoulder_rollは90°といった形で正負逆になっていることが懸念点として考えられます。また両elbowは170°で同じ挙動をしたので、問題ないと思います。

**Comment by yasuohayashibara** [comment]
回転方向に関して基準を作ったほうが良いかもしれません．
左右対称に設定する方法もあれば，左右にかかわらず全て同じ方向に回転するという決め方もできます．

全てを同じ向きにすると，どちらがどちらに回転するということを考えなくても良くなります．
ただし，グリッパが閉じる方向をマイナスにしなければならないなど，少々違和感のある状況になるかもしれません．

サーボモータに合わせるという方法もありますが，これは設定ファイルもしくはサーボモータのパラメータ書き換えで対応できますので，あまり気にしなくても良いかもしれません．

**Comment by Keita1Mori** [comment]
主に右アームをplan＆executeした場合に以下の画像のようにfailedと表示されてしまうことがあります。

![Screenshot from 2024-02-23 15-20-49](https://github.com/open-rdc/orne_or/assets/71181654/74298ff2-aff3-45b5-9c4c-4e47e442d0c0)
![Screenshot from 2024-02-23 15-20-39](https://github.com/open-rdc/orne_or/assets/71181654/b1d6b9bb-2ff9-4bdb-a3f2-710a64609aab)

**Comment by yasuohayashibara** [comment]
ワーニングを見ると，誤差が発生していますということだと思いますので，問題ないかと思います．
（誤差が作業に支障がない範囲であれば）

0.000065radだとすると，誤差は0.003degでワーニングを出しているようですが，実ロボットでは出せない精度ですね．
ワーニングが出続けると動作が緩慢になるおそれがありますので，それが問題となる場合は調査したほうが良いかも知れません．

**Comment by MibuchiYuta** [comment]
@KiyoshiroKawanabe の個人PCや共有PCでも動作を確認できました。

**Comment by MibuchiYuta** [comment]
整理のためこのissueは一旦閉じます。確認のための目標としていたからのペットボトルを持ち上げるタスクに関しては別issue化します。
