### ISSUE TITLE
手先位置を制御するプログラムの作成

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne_or#40]
手先位置を制御するサンプルプログラムを作成する
以下に夏のオープンキャンパスで使用した例を示す．

https://github.com/yasuohayashibara/crane-x7-teaching-playback/

**Comment by yasuohayashibara** [comment]
共有したのでissueを閉じます．

**Comment by Keita1Mori** [comment]
オフィスロボットのアームを制御するためのプログラム作成

**Comment by Keita1Mori** [comment]
上記のサイトの他に以下のサイトも参考にしながら進めている
https://gbiggs.github.io/ros_moveit_rsj_tutorial/manipulators_and_moveit.html
https://opensource-robotics.tokyo.jp/?p=4526

**Comment by Keita1Mori** [comment]
https://github.com/yasuohayashibara/crane-x7-teaching-playback/blob/main/scripts/teaching_playback.py#L21
上記のプログラムを基に作業を行っている。

# 作業
## 変更点
- `#! /usr/bin/env python` ⇒ `#! /usr/bin/env python3`
下のエラー文を解決すべく変更
エラー文：`/usr/bin/env: ‘python’: No such file or directory`

---
- `sudo apt install ros-noetic-moveit`
下のエラー文を解決すべくインストール
エラー文：
```
Traceback (most recent call last):
  File ~/catkin_ws/src/orne_or/orne_or_manipulation/orne_or_manipulator_driver/scripts/manipulator_control.py", line 4, in <module>
    import moveit_commander
ModuleNotFoundError: No module named 'moveit_commander
```


- 参考にしたサイト:https://stackoverflow.com/questions/73703077/ros-attributeerror-module-moveit-commander-has-no-attribute-movegroupcommand

---
## 今行ってる作業と今後の作業について
現状オフィスロボットのアームと参照しているプログラムの使用している名称の違いによるエラーが出ているので、オフィスロボットに対応した名前になるよう編集している。

**Comment by MibuchiYuta** [comment]
ペットボトルのような円柱を環境内に設置する必要がある

**Comment by Keita1Mori** [comment]
# 3/1作業報告
「UnityではじめるROS 人工知能ロボットプログラミング実践入門」にあるソースコードを参考に以下のコードを作成した。
```
#!/usr/bin/env python3
# coding: UTF-8

import sys
from math import pi

import geometry_msgs.msg
from geometry_msgs.msg import Pose
import moveit_commander
import rospy
import tf
from geometry_msgs.msg import Quaternion, Vector3

def main():
    moveit_commander.roscpp_initialize(sys.argv)

    rospy.init_node("manipulator_pose_planner")

    move_group = moveit_commander.MoveGroupCommander("left_arm")

    pose_goal = geometry_msgs.msg.Pose()
    pose_goal.position = Vector3(0.6, 0.2, 0.6)
    q = tf.transformations.quaternion_from_euler(pi, 0, 0)
    pose_goal.orientation = Quaternion(x= q[0], y=q[1], z=q[2], w=q[3])
    move_group.set_pose_target(pose_goal)

    move_group.go(wait=True)

    move_group.stop()
    move_group.clear_pose_targets()

if __name__ == "__main__":
    main()
```

作成した後に`rosrun orne_or_manipulator_driver manipulator_pose_planner.py`を行ったところ以下のエラー文が表示された。
```
[ERROR] [1709278541.796339263, 2420.227000000]: Semantic description is not specified for the same robot as the URDF
[ INFO] [1709278541.799275964, 2420.228000000]: Loading robot model 'orne_or'...
[ INFO] [1709278541.799351270, 2420.228000000]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ WARN] [1709278541.799466306, 2420.228000000]: Link base_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[ WARN] [1709278541.799622763, 2420.229000000]: Link l_sholder_pitch_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[ WARN] [1709278541.799696264, 2420.229000000]: Link l_wrist_roll_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[ WARN] [1709278541.913436335, 2420.265000000]: Link r_sholder_pitch_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[ WARN] [1709278541.913619344, 2420.265000000]: Link r_wrist_roll_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[ WARN] [1709278541.924670214, 2420.265000000]: Could not identify parent group for end-effector 'left_eef'
[ WARN] [1709278541.924759615, 2420.265000000]: Could not identify parent group for end-effector 'right_eef'
[ WARN] [1709278542.069948624, 2420.316000000]: Kinematics solver doesn't support #attempts anymore, but only a timeout.
Please remove the parameter '/robot_description_kinematics/left_arm/kinematics_solver_attempts' from your configuration.
[ WARN] [1709278542.103552260, 2420.331000000]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ WARN] [1709278542.132194818, 2420.341000000]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1709278543.400937271, 2420.866000000]: Ready to take commands for planning group left_arm.
[ INFO] [1709278548.621701235, 2422.817000000]: ABORTED: TIMED_OUT
```

色々調べたところ目標位置に到達不可能だったり、物理的に制限がかかっていて終了していることがわかりました。よって現在のアームで到達可能な姿勢の設定を今後の作業として行います。

**Comment by MibuchiYuta** [comment]
@Keita1Mori 
とりあえずの動作確認ができたら別ブランチで作業していると思うので、プルリク投げてください。

> 色々調べたところ目標位置に到達不可能だったり、物理的に制限がかかっていて終了していることがわかりました。よって現在のアームで到達可能な姿勢の設定を今後の作業として行います。

こちらの問題は別でissueを立てましょう

**Comment by MibuchiYuta** [comment]
gazeboのモデルがまだ動いていないようですので、その問題を解決してください

**Comment by Keita1Mori** [comment]
# 3/17報告
```
#!/usr/bin/env python3
# coding: UTF-8

import sys
from math import pi

import geometry_msgs.msg
from geometry_msgs.msg import Pose
import moveit_commander
import rospy
import tf
from geometry_msgs.msg import Quaternion, Vector3

def main():
    moveit_commander.roscpp_initialize(sys.argv)

    rospy.init_node("manipulator_pose_planner")

    move_group = moveit_commander.MoveGroupCommander("left_arm")

    pose_goal = geometry_msgs.msg.Pose()
    pose_goal.position = Vector3(0.23, 0.27, 0.54)
    q = tf.transformations.quaternion_from_euler(pi, 0, 0)
    pose_goal.orientation = Quaternion(x= q[0], y=q[1], z=q[2], w=q[3])
    move_group.set_pose_target(pose_goal)

    move_group.go(wait=True)

    move_group.stop()
    move_group.clear_pose_targets()

if __name__ == "__main__":
    main()
```

上記のプログラムでアームを動かすことが確認できた。
# [動画](https://www.youtube.com/watch?v=y2qcSC_o5ps)
## 動作手順

1. `roslaunch orne_or_bringup orne_or_manipulator_sim.launch`と`roslaunch orne_or_moveit_config moveit_planner.launch`をそれぞれのタブで起動
2. 別タブで `catkin_ws/src/orne_or/orne_or_manipulation/orne_or_manipulator_driver/scripts` に移動。
3. 移動した後に`rosrun orne_or_manipulator_driver manipulator_pose_planner.py`を投げる

# 気になる点
アームの動作が終えた際に以下のinfoが表示された
`[ INFO] [1710658156.026358743, 81.919000000]: ABORTED: CONTROL_FAILED
`
# 今後
上記のinfoを調べつつ、動くことが確認できたのでプルリクを投げる。
また本プログラムは`rosrun`での動作確認なので`roslaunch`ができるようにlauchファイルの作成を行う。

**Comment by MibuchiYuta** [comment]
#66 の作業もあります

**Comment by yasuohayashibara** [comment]
@Keita1Mori 
スクリプトの場所ですが，ここはドライバを書くところですので，別の場所にしてください．
ドライバは装置を制御するソフトウェアを入れるところで，アプリケーションを入れるところではありません．
あと，[下位]　driver -> controller -> moveit [上位] と層になっていすので，最上位にdriverが位置するのは管理の観点からも問題があります．

https://github.com/open-rdc/orne_or/tree/noetic-devel/orne_or_manipulation/orne_or_manipulator_driver/scripts

**Comment by yasuohayashibara** [comment]
@Keita1Mori 
#77 で一般的なファイルの位置に移動しました．
問題なければマージしてください．

**Comment by HarukiOgawa1** [comment]
@Keita1Mori 
roslaunchで実行できるようにしました。
https://github.com/open-rdc/orne_or/issues/40#issuecomment-2002344140
https://github.com/open-rdc/orne_or/pull/78

**Comment by Keita1Mori** [comment]
# 今後
noetic devel をメインに連続性のあるアームの動作をできるプログラムの引き続き行う。
#66

**Comment by Keita1Mori** [comment]
左腕と右腕を動かすプログラム

[検証動画](https://youtu.be/rnXfV2vG5ek)

## 変更したプログラム
```
#!/usr/bin/env python3
# coding: UTF-8

import sys
from math import pi

import geometry_msgs.msg
from geometry_msgs.msg import Pose
import moveit_commander
import rospy
import tf
from geometry_msgs.msg import Quaternion, Vector3

def main():
    moveit_commander.roscpp_initialize(sys.argv)

    rospy.init_node("dual_manipulator_pose_planner")

    left_arm = moveit_commander.MoveGroupCommander("left_arm")
    right_arm = moveit_commander.MoveGroupCommander("right_arm")

    # 左右のアームの目標姿勢を設定
    left_pose_goal = geometry_msgs.msg.Pose()
    left_pose_goal.position = Vector3(0.23, 0.27, 0.54)
    left_q = tf.transformations.quaternion_from_euler(pi, 0, 0)
    left_pose_goal.orientation = Quaternion(x=left_q[0], y=left_q[1], z=left_q[2], w=left_q[3])

    right_pose_goal = geometry_msgs.msg.Pose()
    right_pose_goal.position = Vector3(0.12, -0.26, 0.54)
    right_q = tf.transformations.quaternion_from_euler(pi, 0, 0)
    right_pose_goal.orientation = Quaternion(x=right_q[0], y=right_q[1], z=right_q[2], w=right_q[3])

    # 左右のアームに対して目標姿勢を設定
    left_arm.set_pose_target(left_pose_goal)
    right_arm.set_pose_target(right_pose_goal)

    # 左右のアームを同時に移動
    left_arm.go(wait=True)
    right_arm.go(wait=True)

    left_arm.stop()
    left_arm.clear_pose_targets()

    right_arm.stop()
    right_arm.clear_pose_targets()

if __name__ == "__main__":
    main()
```

**Comment by Keita1Mori** [comment]
# 4/1の作業
アームが指定の座標に動作した後に初期位置（仮）に戻るプログラムの変更を行った。
[動作の動画](https://youtu.be/70SBS6S8lpI)

以下変更した内容をpushしたもの
https://github.com/open-rdc/orne_or/commit/3c3ebba490ed56786326bb7cccc0dfdcd79de8ff

**Comment by Keita1Mori** [comment]
# 問題点
別issueで報告すべき内容だと思われるのですが、ハンドの開閉プログラムを作成中に調査した際に気になったので報告します。アームを動かす時と同様にハンドの開閉を以下の動画のようにrviz上のmotion planning で角度指定を行った際に左ハンドの開閉だけ動きませんでした。一方右ハンドも左同様に角度指定したところ問題なく動作。
のでハンドの開閉プログラムを作成しながら原因の究明を行う。

[右ハンド開閉動画](https://youtu.be/HhmLiqnvzjU)
[左ハンド開閉動画](https://youtu.be/wi6BVpYTRvE)

**Comment by yasuohayashibara** [comment]
おそらく開発が不十分なところが残っています．
開発中のブランチに解決の手がかりがある可能性もあります．

**Comment by Keita1Mori** [comment]
以下のissueで報告したように、手先の位置を制御するプログラムの作成を行いシミュレーション、実機ともに動作することが確認できました。

https://github.com/open-rdc/orne_or/issues/66#issuecomment-2084293064

**Comment by Keita1Mori** [comment]
# まとめ
ひとまずissueとしての問題が解決したのでcloseする。
また以下に重要なところをまとめておく。

## ros-noetic-moveitのインストール
https://github.com/open-rdc/orne_or/issues/40#issuecomment-1968490127
上記コメントを見るように開発する際にros-noetic-moveitをインストールする必要がある
`sudo apt install ros-noetic-moveit`

## スクリプト
現在アームを動かすためのスクリプトは以下のディレクトリにまとめている
`orne_or_task_executor/scripts`

## ハンドの開閉
以下コメントで左ハンドが開閉していなかった問題ですが、現状角度指定で動いているので問題ないと思います。
https://github.com/open-rdc/orne_or/issues/40#issuecomment-2034026864


不足事項があれば後日追記する。
