### ISSUE TITLE
URDFを更新する

### ISSUE THREAD

**Issue by Keita1Mori** [open-rdc/orne_or#41]
現在使用しているURDFが簡易版なので、CAD図に合わせたURDFファイルに更新する必要がある.

**Comment by yasuohayashibara** [comment]
#46 #48 で対処した．
回転方向や角度，角速度の制限はまだである．

**Comment by yasuohayashibara** [comment]
こちら微調整の段階に入っており，大枠はできたと思いますのでissueを閉じます．
URDFの問題は残っていますが，個別のissueで解決していただければと思います．
