### ISSUE TITLE
実ロボットの肩ピッチ減速が制御に反映されていない

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/orne_or#42]
実ロボットを用いてmove itからマニピュレーターを動作させたときに肩ピッチ軸の角度が指定の角度にならない。これは減速を考慮していない可能性がある

**Comment by yasuohayashibara** [comment]
ここで改善するかは不明だが，少なくとも減速比を記載する部分はある．

https://github.com/open-rdc/orne_or/blob/f8755e793269a288460d50c573f5c3f1f1319f83/orne_or_description/urdf/manipulator.urdf#L141-L150

**Comment by Keita1Mori** [comment]
urdfの減速比を変更したが、肩ピッチの角度に変化はなかった。

**Comment by yasuohayashibara** [comment]
この値が何処に影響するかは調べておいたほうが良いかもしれない．
（思わぬところに影響がでているかもしれないので．）
不要であれば削除したほうが良いと思います．

**Comment by MibuchiYuta** [comment]
私の方でも確認しましたが、mechanicalReductionの値を変えることで実ロボットの動作が変化することはありませんでした。調べましたがmechanicalReductionを用いること以外でカタッピチ減速に対応させるのであればサーボへの出力に乗算するほかなさそうです。

**Comment by yasuohayashibara** [comment]
次は林原での対応になると思いますが，こちらでも再現したいので，検証に用いたコードと結果を記載していただければと思います．

ちなみに場当たり的に対処するのであれば，以下の部分である特定のidのときにだけ数字を何倍かするというコードを入れれば動くと思います．
全く応用のきかないソースコードになりますが．

https://github.com/open-rdc/orne_or/blob/d1fd87f6bc5464e6bd3887ad21d424288fd153d9/orne_or_manipulation/orne_or_manipulator_driver/src/orne_or_manipulator_driver.cpp#L340

**Comment by MibuchiYuta** [comment]
こちらのコミットになります。 
https://github.com/open-rdc/orne_or/commit/d1fd87f6bc5464e6bd3887ad21d424288fd153d9

**Comment by yasuohayashibara** [comment]
場当たり的ですが，こちらを使用すれば解決できると思います．

https://github.com/open-rdc/orne_or/pull/65

**Comment by yasuohayashibara** [comment]
場当たり的ですが， #65 により解決したのでissueを閉じます．
