### ISSUE TITLE
CAD図の変更

### ISSUE THREAD

**Issue by Keita1Mori** [open-rdc/orne_or#5]
現在あるCAD図を現状の仕様に設計の変更を行う必要がある。

**Comment by MibuchiYuta** [comment]
@Keita1Mori @KiyoshiroKawanabe 作業を報告してcloseしてください

**Comment by Keita1Mori** [comment]
# 全体
ネジの干渉がないかチェックするためにネジを追加した

---

# 頭部
緊急非常停止スイッチを搭載するために首の3dプリンターパーツを再設計した。

<img width="193" alt="スクリーンショット 2024-02-07 140411" src="https://github.com/open-rdc/office_robot/assets/71181654/1c2de455-672a-4cf6-b5ff-05b977cfdc05">

---

# 曲げ加工に適応するため再設計
ミスミのmeviyにパーツの製作依頼をお願いしたところ、製作依頼できないという問題点があったため再設計を行った
## ヨー_ヨー_接続フレーム_2_151207修正品_3
曲げ面に対する辺が繋がっていなかったため、繋がるように変更した
<img width="828" alt="スクリーンショット 2024-01-30 192132" src="https://github.com/open-rdc/office_robot/assets/71181654/612d7609-cc5f-418d-b1e0-2abaedd0be50">

## ヨー_ヨー_接続フレーム_151207修正品_2
修正前のモデルは曲げを行う対面の面が平行でなかったため平行になるように変更した
<img width="860" alt="スクリーンショット 2024-01-30 191839" src="https://github.com/open-rdc/office_robot/assets/71181654/62f32814-bd23-48be-ba7b-c25d1e7d96d2">

## 基準フレーム_根元151207修正品_b
変更前では曲げを行う面に対して平行な辺でなかったため、辺になるよう変更した。また曲げを行う角に余裕がなかったため、角に余裕を持たせるように再設計した
<img width="857" alt="スクリーンショット 2024-01-30 191954" src="https://github.com/open-rdc/office_robot/assets/71181654/cfb28f31-bd5a-4abc-9e26-58d8c215cb88">

---

# 直動部設計
オフィスロボットにリニアガイドが使用されていたため、実機に合わせるようCAD図を変更する必要があった。
## 変更点
- リニアガイドの追加
- アルミフレームとリニアガイドを接続するためのL字固定具の追加
- リニアガイドブロックとL字固定具を接続するためにt3の板を追加
<img width="457" alt="スクリーンショット 2024-02-07 134418" src="https://github.com/open-rdc/office_robot/assets/71181654/16174d59-1834-4eae-9445-e6e93957a414">

---

# 直動部駆動部設計
アームを上下するためにサーボを用いた駆動部の設計を行った

<img width="226" alt="スクリーンショット 2024-02-07 134905" src="https://github.com/open-rdc/office_robot/assets/71181654/f754bbe9-4c6a-4a79-a2d8-b2821d4e2940">
