### ISSUE TITLE
オフィスロボット走行能力調査

### ISSUE THREAD

**Issue by Keita1Mori** [open-rdc/orne_or#51]
アームを初期姿勢にした状態で走行できるかを調査するissue
## 検証内容
- 走行可能な段差段差の調査
- スロープ走行の調査

## 動作環境（検討中）
- 操作方法
  - joystick
- 電源
  - バッテリー
- 電源供給
  - バッテリー　⇒　走行部位
 　　　　　　⇒　サーボ
## 必要な物
- [x] joystick
- [x] 変換基板×2

**Comment by Keita1Mori** [comment]
# 回路の配線構成
<img src = "https://github.com/KiyoshiroKawanabe/OfficeRobot-Hardware/assets/71181654/172d52d8-b0cb-4028-a35d-5bff20dd7f0b" width = "900" hight = "500">

# 変換基板その１(計８個）
- 左肩ピッチ ID:21
- 左肩ヨー　ID:22
- 左肘ヨー　　ID:23
- 左手首ヨー　ID:24
- 左手首ピッチ　ID:25
- 左手首ロール　ID:26
- 左手ヨー　ID:27
- 直動部　ID:3

# 変換基板その２(計７個）
- 右肩ピッチ ID:11
- 右肩ヨー　ID:12
- 右肘ヨー　ID:13
- 右手首ヨー　ID:14
- 右手首ピッチ　ID:15
- 右手首ロール　ID:16
- 右手ピッチ　ID:17

# 追記
なお本検証をはじめからバッテリーで行うとショートするなど危険な要素があるため #21 で安定化電源を使った形でアームの検証を最初に行う。
またそれと同時に台車のみで走行可能かの検証も行う。

**Comment by Keita1Mori** [comment]
# 12/10 オフィスロボット走行動画
[走行の様子](https://drive.google.com/file/d/1QNG94Bo6aCFMg4RzfuMOB0ls8oqPNjeK/view?usp=sharing)

## 走行時間
40分46秒
## バッテリー消費
開始時:100%⇒終了時:75%
## 問題点
- 以下の図のようにちょっとした段差で駆動部が浮いて空回りする現象がいくつかの走行箇所でありました。
<img width="500" hight = "500" alt="スクリーンショット 2023-12-11 140008" src="https://github.com/KiyoshiroKawanabe/OfficeRobot-Hardware/assets/71181654/2ecaa680-35ca-472c-9bf0-0d72fa325816">
<img width="500" hight = "500" alt="スクリーンショット 2023-12-11 140028" src="https://github.com/KiyoshiroKawanabe/OfficeRobot-Hardware/assets/71181654/f9d0f91a-dae9-4eb8-bf28-d7996bd1e02d">
<img width="500" hight = "500" alt="スクリーンショット 2023-12-11 140047" src="https://github.com/KiyoshiroKawanabe/OfficeRobot-Hardware/assets/71181654/61638ce3-54e1-48b8-b2f2-87d44aafc1ea">
<img width="500" hight = "500" alt="スクリーンショット 2023-12-11 140106" src="https://github.com/KiyoshiroKawanabe/OfficeRobot-Hardware/assets/71181654/ea6a6612-b3b2-4075-851b-6469e3753e20">
<img width="500" hight = "500" alt="スクリーンショット 2023-12-11 140127" src="https://github.com/KiyoshiroKawanabe/OfficeRobot-Hardware/assets/71181654/70fb1f63-bdea-4520-9956-ca5af8da5233">

**Comment by Keita1Mori** [comment]
# 12/21 orne-box 3走行検証動画
同経路をorne-box 3で問題なく走行できるか検証を行った。
[走行動画](https://drive.google.com/file/d/1bR3QOAbjU_g8jv9RVqO-GJnduSAkJex9/view?usp=drive_link)

## 結果
問題なく走行できることを確認した。

**Comment by KiyoshiroKawanabe** [comment]
パラメータを変更したら、走行できなかった段差やスロープの走行ができた。
[orne_or_setup/config/orne_or.param](https://github.com/open-rdc/orne_or/blob/noetic-devel/orne_or_setup/config/orne_or.param)
だが、パラメータを詰めすぎたためにモータードライバに電流が流れすぎて故障した可能性がある。
下げられる再度パラメータ調整が必要であり、orne boxなどのパラメータを参考に調整を行う。

**Comment by KiyoshiroKawanabe** [comment]
パラメータを調整し、ハッカソンや津田沼チャレンジの準備で動かしていたが、異常なく動作している。
現在のパラメータであれば、必要以上にトルクがでることはないと考えられる。
ロボットの走行能力だが、「学食へのお使い」のタスクで想定される屋外ルートの走行が確認できた。
しかし、段差を登る、下る際には前後に大きく揺れるため、補助として複数人で走行させたほうが安心。
以前、段差やスロープが踏破できなかったのは、台車のパラメータが初期値だったためだと考えられる。

安定感はないが、想定するルートの走行ができることを確認したため、このissueを閉じます。
