### ISSUE TITLE
ペットボトルの把持ができない

### ISSUE THREAD

**Issue by Keita1Mori** [open-rdc/orne_or#52]
左アームを前へならえしたときに500mlのペットボトルを把持しようとしたときに手先が滑ってペットボトルが把持できない問題がある。
動画、画像は後で挿入します。

**Comment by Keita1Mori** [comment]
# 安定化電源の設定値
VOLT:12V     OVP:12.1V
CURR:1.4A   OCP:2.7A
(電圧の方はソフトウェアマニュアルに記載されていた値に設定、電流は研究室にあった安定化電源のデフォルト値をそのまま使用）

# 前へならえの状態での把持
以下の動画が前へならえをした状態でペットボトルを保持させようとした動画になります。
(すべてのサーボをnormalにした状態です)
[動画](https://drive.google.com/file/d/19A7O0Hn2GT8h7fWNDoX4dTuliIXLK2lk/view?usp=sharing)

# ID:25を垂直に挙げた際の把持
またID:25を垂直にあげ保持する動作も確認しました。
約1分48秒(12秒～2分)の間保持できることが確認できましたが、1分48秒間すぎた際にID:27がhold状態のように脱力しました。

電流の初期値（手を放す瞬間）:0.98A
把持時の最大電流値:1.39A

[動画](https://drive.google.com/file/d/1e4j3xWZmNuq9xnp3kp-GDIKljP5K0kuo/view?usp=sharing)

**Comment by Keita1Mori** [comment]
林原先生からのコメント

> 案外電流が流れないことが意外でした．
根本関節を減速している影響が大きいのでしょうか．
電流値だけ見ると無理せずにアームを使った作業ができそうですね．

**Comment by Keita1Mori** [comment]
> 根本関節を減速している影響が大きいのでしょうか．

こちらのコメントですが、肩のピッチ軸の話でしょうか？

**Comment by Keita1Mori** [comment]
林原先生からのコメント
>はい．そのとおりです．

**Comment by Keita1Mori** [comment]
~~こちらの影響を調べる際にアームの根元をピッチ軸のサーボに直接つけて検証する形でしょうか？~~
対面で話したところ検証しないとのこと

**Comment by Keita1Mori** [comment]
# 12/19　検証動画
ハンドでペットボトルが把持できるか、スポンジを使用して再検証を行いました。
(@KiyoshiroKawanabe 使用したスポンジの種類の追記お願いします)

## 動画その1
[検証動画その1](https://drive.google.com/file/d/1y4rI_3rsrViaGL34WV-2Ys8Hkg0s8UWv/view?usp=sharing)
- (動画3:37~)サーボID:21（肩ピッチ)をfreeにしてID:27(ハンドヨー)をnormal状態にしたところ、スポンジなし同様にペットボトルが滑り把持できない状態でした。
- (動画6:24~)サーボID:21（肩ピッチ)をnormalモードにし5度づつ上に挙げるよう角度をつけてテーブルからペットボトルを把持できるかの検証。
- (動画6:51~)サーボID:21(肩ピッチ）を５度挙げたところ、ペットボトルを把持していたID:27のヨー軸のギアがずれた。
- (動画7:19)サーボID:27のLEDが点滅していたためすべてのサーボをフリーにしました。

## 動画その2
[検証動画その2](https://drive.google.com/file/d/13JuXY1z__EIvlKKpPEVPZN2CPW9ND96v/view?usp=sharing)
サーボID:27単体でペットボトルが把持できるかの検証動画。
- (動画1:43)少し持ち上がることが確認できた
- (動画1:53~)もう少しハンドの開き具合を閉めようととしたところギアずれてしまった。
- (動画3:06~)先ほど同様にハンドの開き具合を狭めようとしたところまたギアが外れてしまった。しかしペットボトルの把持は少しできるものの、滑ってしまうことを確認した。

## 今後
今回スポンジを使用したが、今度はもう少しグリップ力の強いものを使用して再検証を行う。
ハンドヨーのギアを固定しているネジの受け(POM)のネジがつぶれているので、切削を行う。

**Comment by Keita1Mori** [comment]
# 12/21 検証
今日再び把持できるか検証を行った。
1.4 Aで検証したところ途中で脱力してしまう状態になったので、3.0Aで再検証したところペットボトルを把持できることを確認しました。
[1.4Aでの検証動画](https://drive.google.com/drive/folders/1DQ-kELqWGwFgLUd911PIgzBVaXXpr9nw)
[3.0Aでの検証動画](https://drive.google.com/drive/folders/1DQ-kELqWGwFgLUd911PIgzBVaXXpr9nw)

**Comment by yasuohayashibara** [comment]
MoveItで試したほうが良いと思います．
B3Mの設定をコメントアウトしていますので，異なった動きになる可能性があります．
ただし，掴むことはできないかもしれませんので，乗せるになるかもしれませんが．．．

以下，コメントアウトの例です．
外せばyamlのパラメータが適用されます．
https://github.com/open-rdc/orne_or/blob/566275190d3705d8070ac833b53e5d6b1a2032cf/orne_or_manipulation/orne_or_manipulator_driver/src/orne_or_manipulator_driver.cpp#L215-L229

**Comment by KiyoshiroKawanabe** [comment]
#66 で作業します。
