### ISSUE TITLE
アーム固定電流不足

### ISSUE THREAD

**Issue by Keita1Mori** [open-rdc/orne_or#56]

**Comment by Keita1Mori** [comment]
前へならえをするために初めに腕のサーボでデイジーチェーンを組み安定化電源に接続し導通させました。
次にB3Mマネージャーを使用しながら順にサーボID21～27をholdしていきました。
その結果が以下の動画になります。
[サーボホールド](https://drive.google.com/file/d/1ZJdWqziwtdtioD-hpm9nRBupzPgZby18/view?usp=sharing)

**Comment by Keita1Mori** [comment]
先ほど話していたnormal,free,holdについて近藤科学のソフトウェアマニュアルに記載されていました。(p.44)
[B3M Series SoftwareManual Command Reference](https://kondo-robot.com/w/wp-content/uploads/B3M_SoftwareManual1.2.0.2.pdf)
なのでフィードバックしながら固定をしたいのでnormalモードで再検証します。

**Comment by Keita1Mori** [comment]
追記サーボに流せる電流は１個のストール電流×サーボの個数
よって片腕に必要な電流は5.4×2+3.6×5=28.8[A]必要になります。
現状使用している安定化電源が出せるアンペアが11[A]までなので30[A]まで出せる安定化を探している。

**Comment by Keita1Mori** [comment]
林原先生からのコメント

> 大電流が必要な場合はバッテリを利用することになります．
ただし，ショートすると全てが壊れるので，トルクがあまり必要ない姿勢で安定化電源で確認してから，バッテリに切り替えると良いと思います．

**Comment by Keita1Mori** [comment]
となると最大11A流せる安定化で腕が前へならえ出来るか検証したのちにバッテリーで試す感じですか？

**Comment by Keita1Mori** [comment]
林原先生からのコメント

> もっと少ない電流から試したほうが良いと思いますが，まずは安定化電源でできるチェックはそちらで行い，その後にバッテリで検証すると良いと思います．
ちなみに，安定化電源は比較的高価で，ちょっとした電源でも10万円を超えますので，気軽には購入できません．

**Comment by Keita1Mori** [comment]
承知しました。また以下のコメントでトルクがあまり必要ない姿勢で確認を行うと頂いたのですが、前へならえの状態でない形で検証するということでしょうか？

> ただし，ショートすると全てが壊れるので，トルクがあまり必要ない姿勢で安定化電源で確認してから，バッテリに切り替えると良いと思います．

**Comment by Keita1Mori** [comment]
VOLT:12V     OVP:12.1V
CURR:1.4A   OCP:2.7A
(電圧の方はソフトウェアマニュアルに記載されていた値に設定、電流は研究室にあった安定化電源のデフォルト値をそのまま使用）

上記の条件を安定化で設定し、サーボに導通させて検証しました。
[動画](https://drive.google.com/file/d/1X8TNiKB1eP7ZaCq2UhYkoFhcSuOS7dM-/view?usp=sharing)

全てのサーボをnormalモードに設定しいる状態です。またLEDライトの点滅なく出力軸ホーンの固定ができていた模様

**Comment by Keita1Mori** [comment]
モータ7個を直列につなぎ、それぞれnormalモードにしていき腕を固定しました

![siseik](https://github.com/KiyoshiroKawanabe/OfficeRobot-Hardware/assets/53420739/69911a75-cca1-4195-a0a6-c00724be7aa5)

写真の姿勢で2分間静止しました。
出力電流1.4A
モータの点滅はありませんでした。
発熱は手首のピッチ軸(サーボID25)で多少確認されました。その他のモータに発熱は見られませんでした。
[動画](https://drive.google.com/file/d/1eWn-5h2XVDHo9E3_beaWg523f8ZP1c1I/view?usp=sharing)

**Comment by Keita1Mori** [comment]
## 左腕のみ前倣えの状態で2分ほど静止しました。
出力電流1.4A
モータの点滅はなく、前の実験同様に手首のピッチ軸で多少の発熱が確認できました。
[動画](https://drive.google.com/file/d/1q_y4JKmc12YaIIJmVTjLufkmOEK0K2Fs/view?usp=sharing)

**Comment by Keita1Mori** [comment]
林原先生からのコメント

> この姿勢で使う限りあまり消費電力が大きくないということですね．
肩関節のトルクがどのようになっているかが気になりますが，電流が上昇していないということは摩擦力で停止しているような状態になっているということでしょうか．
できれば，肩ピッチ関節を動かして，腕を上下させてみたときの電力もできれば計測していただければと思います．
ただし，目標角度を与えると急激に動きますので，ご注意ください．
最悪故障することもありますので，まずは他の関節をフリーにして動作を確認してから他の関節のサーボを入れてください．

**Comment by Keita1Mori** [comment]
以下の二つの動画は腕を±10度傾け２分間静止したときの動画になります。
## 上に10度上げた時
[動画](https://drive.google.com/file/d/1VjkujTSYUAElH4_OCj9T5hnIbxUOCcqE/view?usp=sharing)

初期電流値：0.73A（手を離した瞬間の電流値）
最大電流値：1.2A（２分間静止したときの最大）
LEDの点滅なし
サーボ発熱ID:25

## 下に10度下げた時
[動画](https://drive.google.com/file/d/1oiI5lPTS6HoTPvfQ0_5z9KLgDevZoR6V/view?usp=sharing)

初期電流値：0.74A（手を離した瞬間の電流値）
最大電流値：1.25A（２分間静止したときの最大）
LEDの点滅なし
サーボ発熱ID:25,21

**Comment by Keita1Mori** [comment]
以下の二つの動画は腕を±20度傾け２分間静止したときの動画になります。
## 上に20度上げた時
[動画](https://drive.google.com/file/d/1hDoR-XCwCk0e8uX038I46QCco_hjqIxM/view?usp=sharing)

初期電流値：0.84A（手を離した瞬間の電流値）
最大電流値：1.3A（２分間静止したときの最大）
LEDの点滅なし
サーボ発熱ID:21,25

## 下に20度下げた時
[動画](https://drive.google.com/file/d/1SumVwi44NVxGtNOKDiWAexDsgt8ocbuU/view?usp=sharing)

初期電流値：0.9A（手を離した瞬間の電流値）
最大電流値：1.24A（２分間静止したときの最大）
LEDの点滅なし
サーボ発熱ID:21,25

**Comment by Keita1Mori** [comment]
林原先生からのコメント

> 勘違いがあったようです．
動画を見た感じ静止状態の計測をしているようですが，お願いとしては「動かして」ということです．
位置制御の目標値を0deg -> 10deg -> 0degなどと動かしたときの電流値を計測してくださいという意味です．

> できれば，肩ピッチ関節を動かして，腕を上下させてみたときの電力もできれば計測していただければと思います．

**Comment by Keita1Mori** [comment]
以下の動画は腕を上下に動かしたものになります。
[動画](https://drive.google.com/file/d/1I9uH7BITtWHiCxsdbkjCK5Acotvcr9gf/view?usp=sharing)

**Comment by Keita1Mori** [comment]
# 今後の予定

#51  の検証を行うためにも左アームサーボ＋直動部サーボで初期姿勢ができるかを検証する。右腕が完成したので、左腕同様の検証を行う。

**Comment by Keita1Mori** [comment]
以下の動画は全サーボをnormal状態にしたときの検証になります。
[全サーボnormalモード](https://drive.google.com/file/d/1mP7cVZkW6ffgXWrNVeSXqdR6SsIi95yw/view?usp=sharing)

**Comment by Keita1Mori** [comment]
# 直動部駆動時の電流値
以下のサーボをホールドした状態で、
- ID:21(左肩ピッチ）
- ID:22(右肩ヨｰ）
- ID:11(右肩ピッチ)
- ID:12(右肩ヨｰ)

ID:3直動部を動かした際の動画になります
[直動部上下動](https://drive.google.com/file/d/1qbywCfDH80XzBPcwwzgy096OYd0IZ3te/view?usp=sharing)

**Comment by Keita1Mori** [comment]
林原先生からのコメント

> 動画に加えて一言入れておいてもらえると助かります．
問題無しの場合は，その旨入れておいてくれると，それを前提に見ることができますので．

**Comment by Keita1Mori** [comment]
一応問題なく動作を確認することができました。
ただし懸念点として今回の検証ではb3m manger で-32000〜32000の範囲での検証だったので、今後上下運動する際はプログラムの方で無限回転させる必要がありそうです。

**Comment by Keita1Mori** [comment]
林原先生からのコメント

> 反応遅れましたが，昔作成した記憶があります．
探したのですが，簡単には見つからなかったので，返信ができていませんでした．

こちらに関しては， #60 で対処します．

**Comment by yasuohayashibara** [comment]
他のissueで議論したほうが良いかも知れませんが，MoveItで支えていないと動かないのは電流値不足のおそれがあります．
こちら早期に解決しないとその次の話に進めない気がします．

**Comment by Keita1Mori** [comment]
安定化電源による電源供給でmoveitでの動作確認を行う。

**Comment by MibuchiYuta** [comment]
## moveitを用いた実験

B3M Managerではなくros-noeticの入ったPCから動作させて確認した。画像左下の安定化電源からservo用のhubを通じて左右のアームに電源を供給している。

### 起動時 初期姿勢
![Image](https://github.com/open-rdc/orne_or/assets/53966307/bb148445-e9dc-4bce-80cb-be11b6c281fc)

### 左手を前方に伸ばした場合
![Image](https://github.com/open-rdc/orne_or/assets/53966307/3f960f7d-ac00-44fb-ac09-d3ed94cb35c6)

### 両手を前方に伸ばした場合
![Image](https://github.com/open-rdc/orne_or/assets/53966307/a0e33bdb-ada4-46d0-b8b6-ae349ac4e204)

### 10°肩ピッチを上げた場合
![Image](https://github.com/open-rdc/orne_or/assets/53966307/2ccefa44-9da0-46bd-a882-658d4c48a099)

**Comment by MibuchiYuta** [comment]
実験では最大でも2.5Aを超えることはなかった。コネクタの許容電流を考えても電流を使い過ぎていることはないと考えられる。
#73 のような問題が残っているがハードウェアを今すぐに大きく変更する必要はない。
