### ISSUE TITLE
回路を保護する3Dプリンターパーツ

### ISSUE THREAD

**Issue by Keita1Mori** [open-rdc/orne_or#58]
こちらは回路を保護するための３Dプリンターパーツの作成のissue

**Comment by Keita1Mori** [comment]
林原先生からのコメント

> 加熱する部品は排熱を考えて設計したほうが良いです．
モータドライバなどは密閉すると部品が故障するかもしれませんので，ご注意ください．

**Comment by Keita1Mori** [comment]
@MibuchiYuta 
詳細の情報についてコメントお願いします。コメントが着き次第このissueをcloseする。

**Comment by MibuchiYuta** [comment]
## モータドライバ及び周辺基板用パーツ
モータドライバやdcdcコンバータ、非常停止スイッチ用のリレーなどは配線が風雑であり近くにまとめて固定したい。そのためorne boxで利用されているデータを複数パーツ用に改変するほか、アルミフレームに固定するためのφ5の穴を２つ追加したモデルを @KiyoshiroKawanabe が設計し印刷した。
PLA で印刷したものが以下の写真のものである。

![Image](https://github.com/open-rdc/orne_or/assets/53966307/ad6e7d88-5456-486f-942e-e5085a58e753)

**Comment by MibuchiYuta** [comment]
## 非常停止スイッチ用カバー
ロボットに半固定状態だったスイッチ頭部付近に固定するパーツである。スイッチの他にB3M SC-1040-Aを固定できるようにしている。
![Image](https://github.com/open-rdc/orne_or/assets/53966307/99c7dac6-6e85-4b7a-85c8-7a1c17274baf)

**Comment by MibuchiYuta** [comment]
## サーボモータ回路用パーツ
RS485USB/シリアル変換アダプターとXHコネクター用ハブ　typeAを固定するパーツである。
![Image](https://github.com/open-rdc/orne_or/assets/53966307/e5641252-2015-40bb-b7c8-d3cab892caf1)
