### ISSUE TITLE
既存ロボットの回路の復元

### ISSUE THREAD

**Issue by Keita1Mori** [open-rdc/orne_or#59]
配線をまとめる回路を作成する必要がある。
下のリンクは小川と三渕先輩が調査した回路図になります。下の回路図を元に作る必要がある。
[回路図](https://docs.google.com/presentation/d/1-fDxcfUiEPj5ZaxjKAxQonV4RFpCkGsmQBOoWNVnj1c/edit?usp=sharing)

**Comment by Keita1Mori** [comment]
林原先生からのコメント

> 世の中にはこのようなものもあります．
https://kondo-robot.com/product/02136

**Comment by Keita1Mori** [comment]
こちらに関して、メカニズムの方が復元できたのでこちらのissueで回路の復元をしていく。

**Comment by Keita1Mori** [comment]
# 現状
現在アームと直動部は安定化電源を使用して電気を導通させ問題なく動かせていることが検証のissue #52 #56  などで確認できる。
また車体の方もバッテリーを用いて走行能力調査(#51 )などで問題なく動くことが確認できている。

# 今後
現在アームと車体部分をつないでバッテリーからの電源供給を行っていない。今後使用する上でバッテリーでアーム、車体を駆動できるような電源供給方法を考える必要がある。

# 案
案の一つとして、望月くんに話を聞いたところ以下のようなモジュールを紹介してくれた。
[LT3790 昇降圧型・大電流DC-DCコンバータモジュール](https://strawberry-linux.com/catalog/items?code=13790)

![スクリーンショット 2023-12-14 210748](https://github.com/KiyoshiroKawanabe/OfficeRobot-Hardware/assets/71181654/d92e37d7-ac05-4935-be15-e9f38204282d)

**Comment by Keita1Mori** [comment]
@MibuchiYuta 
上記で記録した回路構成と変わっている箇所がいくつかあると思うので、アップデートお願いします。
アップデート及びコメントがされ次第このissueをcloseする。

**Comment by yasuohayashibara** [comment]
5A(10A)は少ないかも．どこかで総アンペア数を計算していたと思いますが，この手の電源は余裕を持たせたほうが良いです．
24V -> 12Vを生成する場合は，車載用のものが選べると思います．
（適切かどうかは調べてみないと分かりませんが．．．）

https://www.amazon.co.jp/24v-12v-%E5%A4%89%E6%8F%9B/s?k=24v+12v+%E5%A4%89%E6%8F%9B

> 案の一つとして、望月くんに話を聞いたところ以下のようなモジュールを紹介してくれた。
> [LT3790 昇降圧型・大電流DC-DCコンバータモジュール](https://strawberry-linux.com/catalog/items?code=13790)

**Comment by MibuchiYuta** [comment]
現在は以下のような回路で安定して動作しています。

![Image](https://github.com/open-rdc/orne_or/assets/53966307/ff44003f-c44c-44c5-ba3c-101adc697467)

**Comment by MibuchiYuta** [comment]
残されたパーツを合わせて大体の復元は完了しましたのでcloseします
