### ISSUE TITLE
回路の調査

### ISSUE THREAD

**Issue by Keita1Mori** [open-rdc/orne_or#6]

**Comment by yasuohayashibara** [comment]
搭載されていたDCDC
12/24V -> 5Vの変換
5V5A

![IMG_6732](https://github.com/open-rdc/office_robot/assets/5755200/4e7de716-d073-4cf2-be98-926b0ed27c79)

**Comment by yasuohayashibara** [comment]
スイッチ
10Aのサーキットプロテクタ（icartの部品リストに有）

![IMG_6736](https://github.com/open-rdc/office_robot/assets/5755200/5e38bee8-40d4-40db-bb12-7f268b62caa6)

**Comment by yasuohayashibara** [comment]
リレー
OMRON　LY2-D
コイルサージ吸収用　ダイオード形　（コイル仕様DCのみ）
最大許容電圧（V）が定格電圧の110%なので，12V電源でしか駆動できない．24Vだと故障する．

接点電圧・電流の最大値　125V，10A
https://www.fa.omron.co.jp/data_pdf/cat/ly_ds_j_5_15.pdf?id=949

![IMG_6738](https://github.com/open-rdc/office_robot/assets/5755200/4f94f895-f971-471a-9a73-7531e567353b)

**Comment by MibuchiYuta** [comment]
以前 @HarukiOgawa1 @MibuchiYuta で調査した、過去の回路の電源配線図になります。
![Office_robot_回路図](https://github.com/open-rdc/office_robot/assets/53966307/e718f719-9f50-4128-88c0-7fbf888e3681)

**Comment by MibuchiYuta** [comment]
既存回路の調査を終了しましたのでcloseします
