### ISSUE TITLE
物体を掴ませる

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/orne_or#66]
シミュレータで軽い物体を掴ませる。その後実ロボットでからのペットボトルなどを持ち上げさせたい。

**Comment by Keita1Mori** [comment]
gazebo 上にテーブルを設置することができた。
### 設置のやり方

1. 下のコマンドをそれぞれのタブで起動。

```
roslaunch orne_or_bringup orne_or_manipulator_sim.launch
roslaunch orne_or_moveit_config moveit_planner.launch
```
2. gazebo右`insert`タブ内にある`http://models.gazebosim.o...`をクリック
3. クリックすると色々なモデルが選択できるようになるのでそこからtableを選択しgazebo上に設置する。
![Screenshot from 2024-03-17 18-14-12](https://github.com/open-rdc/orne_or/assets/71181654/497680c2-7f16-45fe-80d4-b814e0d6ff9c)

**Comment by HarukiOgawa1** [comment]
gazebo上の実ロボットを動かす方法として，
catkin_ws/src/icart_mini/icart_mini_gazebo/launch/icart_mini.launchを以下のように変更するとgazeboが起動時に実ロボットが配置される場所が変更された．

問題点として，orne_orの方ではなくicart_mini側の値を変更している点である．

変更前
`  <node name="urdf_spawner" pkg="gazebo_ros" type="spawn_model" respawn="false" output="screen"
        args="-urdf -model icart_mini -param robot_description -x -8 -y 13 -z 0 -R 0 -P 0 -Y 0"/>`

変更後
`  <node name="urdf_spawner" pkg="gazebo_ros" type="spawn_model" respawn="false" output="screen"
        args="-urdf -model icart_mini -param robot_description"/>`

![スクリーンショット 2024-03-17 202645](https://github.com/open-rdc/orne_or/assets/71487953/4a1e9dc4-59ff-4fd1-bec5-b2ce3cf921e0)

**Comment by KiyoshiroKawanabe** [comment]
こちらのissueに気付かず、作業場所である会議室のworldを作成しました。https://github.com/open-rdc/orne_or/commit/50e65fc67c35d2b2db197f2b2c7842e6c5c9b9b2
worldの作成には、[こちらのサイト](https://wisteriahill.sakura.ne.jp/CMS/WordPress/2022/06/19/ros-self-made-robot-world-navigation-2-5-making-world/)を参考にしました。

部屋の寸法は図ったのであっていると思います。必要があれば使ってください。
orne_or/orne_or_bringup/worldsの中に入っています。
![image](https://github.com/open-rdc/orne_or/assets/53420739/2a643996-1e03-4519-92f5-01e46d205609)

**Comment by KiyoshiroKawanabe** [comment]
ペットボトルを左腕でつかみに行くスクリプトを作成しました。
https://github.com/open-rdc/orne_or/blob/bottle-catch/orne_or_task_executor/scripts/bottle_catch.py
すべて角度を指定してうごかしています。
シミュレーター上では添付の動画のように動作しています。
実ロボットでの検証はbringupの時点で、右腕のサーボがすべて点滅し力が入らかったため検証できていません。

動作の様子→https://youtu.be/7ir-3WC9U7o

**Comment by Keita1Mori** [comment]
# 4/29 進捗報告
ペットボトルを右腕で掴むスクリプトを作成しました。
https://github.com/open-rdc/orne_or/blob/bottle-catch/orne_or_task_executor/scripts/manipulator_right.py

## 作成したスクリプトの詳細説明

- こちらのスクリプトでは指定した座標を以下のようにプログラム上に記入して、アームを指定した座標に移動するように制御させています。

```
    right_wrist_goal = PoseStamped()
    right_wrist_goal.header.frame_id = "world"
    right_wrist_goal.pose.position.x = 0.4517
    right_wrist_goal.pose.position.y = 0.0318
    right_wrist_goal.pose.position.z = 0.568653
```

---

- また手首(ID:16)の回転は以下のorientationのところを以下のように指定することで90度回転するようになりました。

`    right_wrist_goal.pose.orientation = Quaternion(*tf.transformations.quaternion_from_euler(0, -(pi / 2), pi))`

---

- 最後にペットボトルを掴む際のハンドを閉じるためのスクリプトは以下に示します。（10度閉じるよう角度指定をしています）

```
target_joint_positions = [10 * (pi / 180)]
right_hand.set_joint_value_target(target_joint_positions)
right_hand.go(wait=True)
```

## シミュレーション時の動画
[0429_manipulator_right_control](https://drive.google.com/file/d/1op2AlmgyAMiOW0xyfBOD6_ESIzAGWDnd/view?usp=drive_link
)

**Comment by MibuchiYuta** [comment]
#85 #86 で物体の検出をおこなっています。

**Comment by Keita1Mori** [comment]
# GW期間中の開発
上記のスクリプト同様におにぎりを掴むためのスクリプトを作成しました。
[manipulator_right_onigiri.py](https://github.com/open-rdc/orne_or/blob/bottle-catch/orne_or_task_executor/scripts/manipulator_right_onigiri.py)

## 実機での検証動画
- [動画その1](https://drive.google.com/file/d/1JN-f7NNiqWQKLdvp94YBCsMDZnQfLoXx/view?usp=drive_link)
  - おにぎりを掴んだ後に初期位置に戻るスクリプトの検証
- [動画その2](https://drive.google.com/file/d/1N6gbGZ7DNn6qwq5np3JZ6GAks5Kn6Kaw/view?usp=drive_link)
  - おにぎりを掴んだ後にアームを下に下ろして黒い箱の上に収納させるスクリプトの検証

**Comment by KiyoshiroKawanabe** [comment]
空のペットボトルと100円玉を掴ませました。
[空のペットボトル](https://youtube.com/shorts/jCZ8hLzsQcI?feature=share)

[100円玉](https://youtu.be/OWSyzPQntHY)※危険なのでロボットの可動域に入らない。

**Comment by Keita1Mori** [comment]
# まとめ
ひとまずissueとしての問題が解決したのでcloseする。
また以下に重要なところをまとめておく。

## スクリプト
マニピュレータを動かすスクリプトは以下のディレクトリにまとめている
`orne_or_task_executor`

またスクリプトの詳細については以下のissueを確認
https://github.com/open-rdc/orne_or/issues/40

## マニピュレータ把持の様子
### ペットボトル把持
詳細については以下リンクのコメントを参照
- 角度指定
  - https://github.com/open-rdc/orne_or/issues/66#issuecomment-2082646597
- 座標指定
  - https://github.com/open-rdc/orne_or/issues/66#issuecomment-2084293064
### おにぎりの把持
- 角度指定
  - https://github.com/open-rdc/orne_or/issues/66#issuecomment-2095116424
### 100円玉の把持
  - https://github.com/open-rdc/orne_or/issues/66#issuecomment-2107684698

不足事項があれば後日追記する。
