### ISSUE TITLE
ハッカソン2024春の記録

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/orne_or#69]
研究室のメンバーでハッカソンを行う。その記録をする

**Comment by kyo0221** [comment]
kinect v1を使用してRGB画像, 深度画像を出力することができた.また, 知能ロボコンの際に使用していた3色のボールを見つけてそれぞれの色を検知し, ボールの輪郭に線を描くプログラムを作成した.

**Comment by MibuchiYuta** [comment]
# 目標と分担
今回のハッカソンでは的当てをロボットにさせることにした

![IMG_1655](https://github.com/open-rdc/orne_or/assets/53966307/70ca8f70-9249-4726-aede-50c54552fe01)

**Comment by HarukiOgawa1** [comment]
windows11のwsl2のUbuntu 20.04上で環境構築を行った．

**Comment by MibuchiYuta** [comment]
#22 の作業を終了させ、gazebo上でも実ロボットでも同じ動作するようになった。

**Comment by 21C1072takahashishoku** [comment]
Pythonの音声認識ライブラリであるSpeechRecognitionを使用して音声を認識し、テキストファイルとして出力できるようになった。

**Comment by KiyoshiroKawanabe** [comment]
津田沼2号館三階の自立移動と308教室の地図を作成した。B3山本君と

**Comment by MibuchiYuta** [comment]
udev ruleの変更を行い、kondo rs484変換を接続すると/dev/sensors下になるようにした。

**Comment by KiyoshiroKawanabe** [comment]
3階の会議室で自立移動させた
意味なくなったけどリアルセンス触ってた
林原先生のエンドエフェクタを動作させるプルリクを確認してマージした

**Comment by kyo0221** [comment]
yolov5を通してkinect v1を使用することができた.物体を検出してバウンディングボックスを表示させることができた.
今後のやること
・バウンディングボックスの中の深度の平均を出すことで物体との距離を計算できるようにする.
・ボールの色を学習させるため画像を撮ってアノテーションする.

**Comment by 21C1072takahashishoku** [comment]
入力された音声からボールの色、的の色を抽出することができるようになった。
書いたプログラムをrosで使用できるようにした。

**Comment by MibuchiYuta** [comment]
@shin0410 #40 の作業をお願いします。

**Comment by yasuohayashibara** [comment]
#68 をシミュレータで使用する場合は，以下が必要
gazeboではURDFのmimicが無視されるので，プラグインで対応しなければならない．
（これに関する記述がほとんどなかったので，解決までに半日程度必要だった．．．）
https://github.com/open-rdc/orne_or/blob/fc01556374a8b837ca3a1c964c57d2735ff7be91/orne_or_bringup/package.xml#L14
※検証不足なので，インストール時にエラーが生じるおそれあり．

手動で入れる場合はおそらくこのようなコマンド

```
sudo apt install ros-noetic-roboticsgroup-upatras-gazebo-plugins
```

**Comment by Keita1Mori** [comment]
本日行った作業。
https://github.com/open-rdc/orne_or/issues/40#issuecomment-2002344140

今後の作業として #66 を行う。
テーブルの設置が完了。
https://github.com/open-rdc/orne_or/issues/66#issuecomment-2002374716

**Comment by kyo0221** [comment]
kinectv1を使用してバウンディングボックス内での深度の平均を求めることで物体との距離が測れるようになった.また, 学習用の画像データを収集してアノテーションを行った.

**Comment by 21C1072takahashishoku** [comment]
音声認識でスタート、ボールと的の色を抽出することができるようになった。
スタートが検知できるまではボールと的の色の抽出をしないようにした。

**Comment by MibuchiYuta** [comment]
問題解決 
- #71

実ロボットでの確認と修正
- #72 #74

今後の作業
- #67 
- #73

**Comment by MibuchiYuta** [comment]
## 残りタスクの確認
3日目の折り返しなので残りの作業を確認する。
### 音声認識
- roslaunchで起動できるようにする @21C1072takahashishoku 
### 物体認識
- ボール学習データのチェック @kyo0221 
- 的データの学習回す @kyo0221 
- カメラからではなく腕の付け根から物体までの距離を出す @kyo0221 
- 移動目標位置を決定する仕組み @KiyoshiroKawanabe 
- (倒れているペットボトルの向きを検出 @kyo0221 )
### マニピュレーション
- #40  @Keita1Mori @HarukiOgawa1 
- #66 @Keita1Mori @HarukiOgawa1 
- 的に向かってボールを投げる動作をさせる 
### 移動
- 
### その他
- #67 @MibuchiYuta

**Comment by kyo0221** [comment]
3/17に取得した学習用画像データの学習が終わったため学習データを活用してyolov5を使用した.赤いボールは正しく認識できたが青いボールと黄色いボールの判定が入れ替わってしまった.その後新しく画像を収集し, 今度は的であるペットボトルも含めてアノテーションを行った.前回の学習データを使用した転移学習を行ったが結果はすべての色のボールが間違って検知されている結果になった.kinect k1を使用して取得した深度データを使って認識した物体の3次元座標を表示させるようにした.現在は深度だけではボールの詳しい位置が掴めないためロボットの向きをボールや的に対して真っ直ぐにするプログラムを作成している.
今後の予定
・的を含めたボールの再学習
・作成中のプログラムを完成させる

**Comment by MibuchiYuta** [comment]
- #67 に取り組んでいた。
→進展はあり。 orne_or_manipulator.launchで実ロボットの腕を初期姿勢にさせた後にテレオペで台車が動いた。
名前空間の問題らしく、icart_mini_control.launchに名前空間の設定ができない。

**Comment by KiyoshiroKawanabe** [comment]
- world作成した　https://github.com/open-rdc/orne_or/issues/66#issuecomment-2003132038

山下君が取得したボールの座標は、カメラ座標系なので、それをロボット座標系に変換する必要がある。が、座標系を管理するtf、に手こずっている。

**Comment by 21C1072takahashishoku** [comment]
音声認識のプログラムをlaunchファイルで実行することができるようになった。

**Comment by HarukiOgawa1** [comment]
マニピュレーション
- #40
roslaunchで実行できるようにした。現状指定した座標にロボットアームを動かしているのでロボットハンドが固定してものをつかめる姿勢になるようにしたい。また、一連の動作をつなげて実行できるようにしたい。

**Comment by shin0410** [comment]
cudaの設定をしてしまっていましたすみません

**Comment by MibuchiYuta** [comment]
## 振り返り
closeする前に軽く振り返りを残します
### できたこと
- アーム関連のissueの消化
- 音声認識によるパッケージとその後のボール認識
- ボールの座標の取得
- 目標座標へのアーム先端の移動
- 室内での自律移動
### できなかったこと
- 目標タスクの遂行
- 目標座標にあるボールのピッキング
