### ISSUE TITLE
シミュレーション環境でのエンドエフェクタの挙動

### ISSUE THREAD

**Issue by KiyoshiroKawanabe** [open-rdc/orne_or#70]
シミュレーション環境でエンドエフェクタを操作できるようになったが、左アームのエンドエフェクタの挙動が図のようになっている。
moveitでは動いていない方の、l_hand_right_jointにも角度司令は送っているように見えるが、gazeboでは動きが反映されていない。
<img src="https://github.com/open-rdc/orne_or/assets/53420739/acbf06e0-720f-4eb5-b5da-bc4a173ca4b3" width=600>
![Screenshot from 2024-03-17 09-55-41](https://github.com/open-rdc/orne_or/assets/53420739/c727815c-81c6-4efe-994f-bef9e98001a5)

**Comment by yasuohayashibara** [comment]
対処法を，こちらに記載しておきました．
https://github.com/open-rdc/orne_or/issues/69#issuecomment-2002182511

**Comment by MibuchiYuta** [comment]
解決したためcloseします
