### ISSUE TITLE
音声認識をさせる

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/orne_or#75]
#69 で音声認識をさせることになった。その作業を記録する

**Comment by 21C1072takahashishoku** [comment]
```
pip install SpeechRecognition

```

**Comment by 21C1072takahashishoku** [comment]
> ```
> pip3 install SpeechRecognition
> ```

**Comment by 21C1072takahashishoku** [comment]
環境構築
インストール
> > ```
> > pip3 install SpeechRecognition
>>do apt-get install portaudio19-dev
>>sudo apt-get install python-pyaudio python3-pyaudio
>>pip3 install pyaudio
> > ```

**Comment by 21C1072takahashishoku** [comment]
> 音声認識をするにあたって以下のパッケージを使用した
>環境構築
>インストール
> > > ```
> > > pip3 install SpeechRecognition
> > > do apt-get install portaudio19-dev
> > > sudo apt-get install python-pyaudio python3-pyaudio
> > > pip3 install pyaudio
> > > ```

**Comment by 21C1072takahashishoku** [comment]
> > 音声認識をするにあたって以下のパッケージを使用した
> > 環境構築
> > >インストール
> > > > ```
> > > > pip3 install SpeechRecognition
> > > > do apt-get install portaudio19-dev
> > > > sudo apt-get install python-pyaudio python3-pyaudio
> > > > pip3 install pyaudio
> > > > ```

**Comment by 21C1072takahashishoku** [comment]
>音声認識をするにあたって以下のパッケージを使用した
 > 環境構築
 > > インストール
> > > ```
> > > pip3 install SpeechRecognition
> > > do apt-get install portaudio19-dev
> > > sudo apt-get install python-pyaudio python3-pyaudio
> > > pip3 install pyaudio
> > > ```

**Comment by 21C1072takahashishoku** [comment]
音声認識をするにあたって以下のパッケージを使用した
 環境構築
 > インストール
 > > ```
> > pip3 install SpeechRecognition
> > do apt-get install portaudio19-dev
> > sudo apt-get install python-pyaudio python3-pyaudio
> > pip3 install pyaudio
> > ```

**Comment by 21C1072takahashishoku** [comment]
> 音声認識をするにあたって以下のパッケージを使用した 環境構築
> 
> > インストール
> > > ```
> > > pip3 install SpeechRecognition
> > > do apt-get install portaudio19-dev
> > > sudo apt-get install python-pyaudio python3-pyaudio
> > > pip3 install pyaudio
> > >sudo apt install xterm gnome-terminal konsole
> > > ```

**Comment by 21C1072takahashishoku** [comment]
> > > 音声認識をするにあたって以下のパッケージを使用した 環境構築
> > > > インストール
> > > > > ```
> > > > > pip3 install SpeechRecognition
> > > > > sudo apt-get install portaudio19-dev
> > > > > pip3 install pyaudio
> > > > > sudo apt install xterm gnome-terminal konsole
> > > > > ```

**Comment by 21C1072takahashishoku** [comment]
ハッカソン全体で行ったこと：
- 音声認識を使用し、開始の合図やボールの色を判断させた。
- 開始の合図やボールの色を、publisherから送信して、それをtopicとしてlistenerに受信させた。

**Comment by 21C1072takahashishoku** [comment]
> ハッカソン全体で行ったこと：
> 
> * 音声認識を使用し、入力された音声から開始の合図やボールの色を判断させた。
> * 開始の合図やボールの色を、publisherから送信して、それをtopicとしてlistenerに受信させた。

**Comment by MibuchiYuta** [comment]
ハッカソンが終了したため一度closeします
