### ISSUE TITLE
物体認識をさせる

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/orne_or#76]
#69 でボールとペットボトルを認識する必要がある。ボールは色の見分けとロボットからの距離、ペットボトルは向きとロボットからの距離を取得できっるようにする。

**Comment by kyo0221** [comment]
物体認識に際してカメラはkinect for windows v1を使用した.
kinectを使用するにあたって以下のパッケージをインストールした.
https://github.com/ros-drivers/freenect_stack
インストールする際に参考にしたもの
https://rospibot.azw.pt/ros-noetic-kinect-xbox-360/

物体の認識はYolo v5で行うことにした.yoloをROSで動作させるためにyolov5_pytorch_rosのインストールも行った.
互換性の問題でyolo v5のバージョンは4.0になっている.
https://github.com/ultralytics/yolov5/tree/v4.0
https://github.com/raghavauppuluri13/yolov5_pytorch_ros

カメラ画像は
roslaunch freenect_launch freenect.launch
を起動した状態でrvizを使用して見ることができる
roslaunch yolov5_pytorch_ros detector.launch
も起動することでカメラ画像でyolov5の物体認識ができる.

物体との距離は深度画像から得ることにした.
yoloで取得した物体の周りに表されるバウンディボックスの範囲内で深度の平均値を求めることにより物体との距離を測った.

**Comment by kyo0221** [comment]
アノテーションには以下のものを使用した
https://github.com/HumanSignal/labelImg/tree/master

**Comment by kyo0221** [comment]
launchを立ち上げてrvizでカメラ画像を見ようとしてもNo imageと表示されることがある.topicは出ているが値が入っていない状態.原因は不明

バッテリーを変えることで解決した.カメラに緑色の点滅が出ているときにカメラ画像を見ることができた.

**Comment by MibuchiYuta** [comment]
ハッカソンが終了したため一度closeします

**Comment by KiyoshiroKawanabe** [comment]
![Screenshot from 2024-04-28 13-13-43](https://github.com/open-rdc/orne_or/assets/53420739/260ec65b-30e4-4721-90b4-224f5830cb75)

```
roslaunch freenect_launch freenect.launch
roslaunch yolov5_pytorch_ros detector.launch
```
２つのlaunchを起動させ、別ターミナルでrvizを起動しrviz上で認識しているか確認できる。
By topicの/detections_image_topicのImageをAddすると画像のように確認できる。
