### ISSUE TITLE
ros_control関連のエラー

### ISSUE THREAD

**Issue by KiyoshiroKawanabe** [open-rdc/orne_or#83]
## 発生している問題
``` 
roslaunch orne_or_bringup orne_or_manipulator_sim.launch  
roslaunch orne_or_moveit_config moveit_planner.launch
```
上記コマンドを実行し、rviz上でアームの関節角度を指定し、Plan & Executeを実行してもGazebo上で動作を確認できない。

## エラー文
エラーとそれの意味を[こちら](https://docs.google.com/document/d/1_hpIHHsI-JNPk4Nl-CWL6niA6v6sdct_maBvUlfSPV4/edit?usp=sharing)にまとめました
pidゲインが設定されていない、コントローラが見つからないなど。

## 動作環境
共有ノートpc thinkPad
noetic-devel, hackathon-2024-springブランチで同じように実行ができないことを確認。

**Comment by KiyoshiroKawanabe** [comment]
こちらの問題に対処するため、noetic-develからros-controlというブランチを切って対処します

**Comment by Keita1Mori** [comment]
全く動かないという識識であっていますでしょうか？
現状自分の環境で動くととは確認出来ているのですが
## 動作確認の環境
- PC: Panasonic Let's Note
- Ubuntu: 20.04
- Branch: noetic-devel

[動作確認画画](https://youtu.be/Cp3f_gWiP50
)

**Comment by KiyoshiroKawanabe** [comment]
build通して確認する

**Comment by KiyoshiroKawanabe** [comment]
catkin buildして、sourceを通したら動きました。ので、issue閉じてブランチも削除します。
