### ISSUE TITLE
世の中にあるオフィスロボットに利用できるソフトウェア調査

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/orne_or#89]

**Comment by YugoNishio** [comment]
#90 調査結果
TIAGoのROSパッケージで実装されているものが，オフィスロボットの基礎的な要素を含んでいる事が分かった．

**Comment by YugoNishio** [comment]
TIAGoのROSパッケージの構成で，ロボットに行わせるシナリオを十分達成できると判断したため，調査を終了します．
