### ISSUE TITLE
組み立て作業

### ISSUE THREAD

**Issue by Keita1Mori** [open-rdc/orne_or#9]

**Comment by MibuchiYuta** [comment]
@KiyoshiroKawanabe @Keita1Mori 報告をお願いします。

**Comment by Keita1Mori** [comment]
#5 を元に発注したパーツによる復元の組み立てを行った。
<img width="709" alt="スクリーンショット 2024-01-30 204722" src="https://github.com/open-rdc/office_robot/assets/71181654/21286773-72f6-45f6-83ef-423a80a9782a">
<img src = "https://github.com/open-rdc/office_robot/assets/71181654/bfc55c32-d644-4b66-bbbb-7d47bbd2ddc4" width = "500" height = "500">
# 組み立て手順

 ## 1.リニアガイドブロックとL字固定具を締結

<img width="272" alt="スクリーンショット 2024-02-07 152644" src="https://github.com/open-rdc/office_robot/assets/71181654/d190450d-60ba-40c6-9a61-07c7c523fe60">

### 必要パーツ
- 赤：M3×8　16個
  - （※リニアガイドブロックに締結する際きつく締めすぎないこと、締めすぎるとリニアガイドの劣化になるため)
- オレンジ：M5×10　4個
  - （なるべくきつく締めること、完成後の締結が難しいため)
- 緑：M2×6　4個
- HBLFSDK5-SEP　２個（L字固定具）
- LR固定用　２個

<img width="278" alt="スクリーンショット 2024-02-07 152917" src="https://github.com/open-rdc/office_robot/assets/71181654/7432f72f-6063-4c0d-8cdc-10180d615fab">


## 2.アルミフレームとL字固定具を締結
<img width="821" alt="スクリーンショット 2024-02-07 160015" src="https://github.com/open-rdc/office_robot/assets/71181654/6dbf1eb8-e5ac-4799-99a5-d735b755db71">

### 必要パーツ
- オレンジ：M5×10　４個
- HNTP5-5　４個　(締結するためにアルミフレームの溝に入れる）
- HFS5-2040　１個（アルミフレーム）

## 3.基準フレーム_根元151207修正品_bを締結とアルミフレームを締結
<img width="593" alt="スクリーンショット 2024-02-07 162552" src="https://github.com/open-rdc/office_robot/assets/71181654/df163544-723d-47d6-9625-c6ab4547e577">

### 必要パーツ
- オレンジ：M5×6　４個（※サーボ挿入後、再締結するのが難しいので、きつく締めること)
- HNTA5-5　４個（締結するためにアルミフレームの溝に入れる)
- 基準フレーム_根元151207修正品_b　２個

## 4.基準フレーム_根元151207修正品_bにサーボを締結
なおサーボをギアボックスに締結する前にサーボに0.75_30_S75B 30B+0306を取り付けておく

<img width="518" alt="スクリーンショット 2024-02-07 170111" src="https://github.com/open-rdc/office_robot/assets/71181654/50c63187-666b-490d-89dd-4f50c37b17b3">

### 必要パーツ
- B3M-SC-1170-A　2個
- シアン：M2.6×8　８個（ギア固定用）
- シアン：M2.6×15　２個（出力軸側サーボ締結用ネジ）（※角以外のところを締結するとピッチの部品と干渉するので、角の方だけ締結)
- シアン：M2.6×20　４個（サーボホーン側締結用ネジ）（※両方締結）
<img width="336" alt="スクリーンショット 2024-02-07 170630" src="https://github.com/open-rdc/office_robot/assets/71181654/bf16d128-4b88-4088-b816-7dc9f80a337f">

## 5.扇型ピッチギアとギア_サーボ接続フレーム_2_151207修正品の締結
<img width="467" alt="スクリーンショット 2024-02-07 171748" src="https://github.com/open-rdc/office_robot/assets/71181654/6e5ff88b-63d2-4816-8709-3d3119d84b4a">

### 必要パーツ
- ギア_サーボ接続フレーム_2_151207修正品　２個
- FL606ZZ　２個
- 0.75_120_S75B 120A-0315　２個
- ギア_サーボ接続フレーム　２個
- D5060-0550　２個
- BA3047　２個
- スラスト高さ調整　２個
- 赤：M3×6　８個（※取り付け後締結するのが難しくなるため、きつく締める）
### 断面図
<img width="860" alt="スクリーンショット 2024-02-07 173444" src="https://github.com/open-rdc/office_robot/assets/71181654/91e3ce1b-de5a-4bb1-bf7e-fa807ce4a7d1">

## 6. 手順5で締結したものをアルミフレームに締結
<img width="447" alt="スクリーンショット 2024-02-07 174228" src="https://github.com/open-rdc/office_robot/assets/71181654/06975c6f-e68b-4bfd-8613-4c607fb61c4c">

### 必要パーツ
- オレンジ：M5×15 ２個（※取り付け後締結するのが、難しくなるため、きつく締める)

## 7.ギア_サーボ接続フレーム_2_151207修正品とアームの締結
<img width="414" alt="スクリーンショット 2024-02-07 174959" src="https://github.com/open-rdc/office_robot/assets/71181654/0de28d36-c629-4d64-bd00-972d121dc6aa">

### 必要パーツ
- シアン：M2.6×15　4個（※出力軸側）
- シアン：M2.6×20　4個（※サーボホーン側）

**Comment by Keita1Mori** [comment]
# 直動駆動部組み立て
アルミフレームを上下させるために駆動する部分の組み立て
## 必要パーツ
- gear1　１個
- B3M-SC-1170-A　１個
- gear_Jig　１個
- オレンジ：M5×6　２個
- シアン：M2.6×10　４個
- シアン：M2.6×15　２個
- ワッシャー：UUW-0509-15　1個（リニアガイド側（上）のネジ頭とgear_Jigの間にかませる）
- HNTA5-5　２個（後入れできるタイプなのでそのままアルミフレームの溝に挿入)



<img width="449" alt="スクリーンショット 2024-02-08 175729" src="https://github.com/open-rdc/office_robot/assets/71181654/6403461c-3aff-4f00-8c2f-ad49537938f7">

**Comment by Keita1Mori** [comment]
再度必要な場合はreopenする。
